from __future__ import annotations

import os
import subprocess
from pathlib import Path
from types import SimpleNamespace

import pytest

import skillpack_tools.generate as generate
from skillpack_tools.publication import _generated_output_records
from skillpack_tools.util import SkillpackError
from skillpack_tools.validate import raise_for_result, validate_repository

_WORKER_SNAPSHOTS: dict[Path, generate.GeneratedFiles] = {}


@pytest.fixture()
def bound_snapshot(generated_repo_copy: Path) -> generate.GeneratedFiles:
    """Build one snapshot per worker; the repository fixture restores the same exact tree."""

    snapshot = _WORKER_SNAPSHOTS.get(generated_repo_copy)
    if snapshot is None:
        result = generate.apply_generated_files(generated_repo_copy, check=True)
        assert isinstance(result, generate.GeneratedChanges)
        snapshot = result.generated_files
        _WORKER_SNAPSHOTS[generated_repo_copy] = snapshot
    return snapshot


@pytest.mark.parametrize(
    "relative,mutation",
    [
        ("evals/routing-boundaries.json", "bytes"),
        ("schemas/routing-boundaries.schema.json", "bytes"),
        (
            "packs/python/best-practices/skills/python-project-layout/references/guide.md",
            "bytes",
        ),
        (
            "packs/python/best-practices/skills/python-project-layout/references/guide.md",
            "index-mode",
        ),
    ],
)
def test_generated_snapshot_rejects_changed_canonical_inputs(
    generated_repo_copy: Path,
    bound_snapshot: generate.GeneratedFiles,
    relative: str,
    mutation: str,
) -> None:
    root = generated_repo_copy
    path = root / relative
    if mutation == "bytes":
        path.write_bytes(path.read_bytes() + b"\n")
    else:
        subprocess.run(
            [
                "git",
                "-c",
                "core.longpaths=true",
                "-C",
                str(root),
                "update-index",
                "--chmod=+x",
                relative,
            ],
            check=True,
        )

    with pytest.raises(SkillpackError, match="snapshot inputs changed"):
        generate._reconcile_generated_files(root, check=True, expected=bound_snapshot)


@pytest.mark.parametrize(
    "relative,content",
    [
        (".claude-plugin/marketplace.json", b"tampered generated bytes\n"),
        ("dist/dev/unexpected-generated-file.txt", b"stale generated bytes\n"),
    ],
)
def test_generated_snapshot_rejects_generated_tree_drift(
    generated_repo_copy: Path,
    bound_snapshot: generate.GeneratedFiles,
    relative: str,
    content: bytes,
) -> None:
    root = generated_repo_copy
    path = root / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(content)

    with pytest.raises(SkillpackError, match="Generated files are missing or stale"):
        generate._reconcile_generated_files(root, check=True, expected=bound_snapshot)


def test_snapshot_is_unbound_when_generation_inputs_race(
    generated_repo_copy: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    root = generated_repo_copy
    boundary = root / "evals" / "routing-boundaries.json"
    original = generate.build_generated_files
    captured: list[generate.GeneratedFiles] = []

    def racing_build(candidate_root: Path) -> generate.GeneratedFiles:
        result = original(candidate_root)
        captured.append(result)
        boundary.write_bytes(boundary.read_bytes() + b"\n")
        return result

    monkeypatch.setattr(generate, "build_generated_files", racing_build)
    with pytest.raises(SkillpackError, match="Generation inputs changed during"):
        generate.apply_generated_files(root, check=True)
    assert captured and captured[0]._source_root is None
    assert captured[0]._source_state is None


def test_snapshot_cannot_cross_repository_boundaries(
    bound_snapshot: generate.GeneratedFiles,
    tmp_path: Path,
) -> None:
    with pytest.raises(SkillpackError, match="not bound to this repository"):
        generate._verify_generation_snapshot(
            tmp_path,
            bound_snapshot,
            bound_snapshot._source_state,
        )


def test_reconciliation_and_validation_build_generated_files_once(
    generated_repo_copy: Path,
    bound_snapshot: generate.GeneratedFiles,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    root = generated_repo_copy
    calls = 0

    def counted_build(_root: Path) -> generate.GeneratedFiles:
        nonlocal calls
        calls += 1
        clone = generate.GeneratedFiles()
        for relative, content in bound_snapshot.items():
            clone.add(relative, content, mode=bound_snapshot.modes[relative])
        return clone

    monkeypatch.setattr(generate, "build_generated_files", counted_build)
    result = generate.apply_generated_files(root, check=True)
    assert isinstance(result, generate.GeneratedChanges)
    result = validate_repository(
        root,
        check_generated=True,
        strict_placeholders=True,
        _generated_files=result.generated_files,
    )
    raise_for_result(result)
    assert calls == 1


def test_published_inputs_ignore_replace_and_graft_semantics_and_bind_exact_objects(
    tmp_path: Path,
) -> None:
    root = tmp_path / "repository"
    root.mkdir()

    def git(*arguments: str) -> str:
        return subprocess.check_output(
            ["git", "-C", str(root), *arguments],
            text=True,
        ).strip()

    subprocess.run(["git", "init", "-q", str(root)], check=True)
    git("config", "user.email", "fixture@example.com")
    git("config", "user.name", "Fixture")
    (root / "base.txt").write_text("base\n", encoding="utf-8")
    git("add", "base.txt")
    git("commit", "-q", "-m", "base")

    pack_path = root / "packs" / "python" / "example"
    skill_path = pack_path / "skills" / "example-skill"
    skill_path.mkdir(parents=True)
    manifest_relative = "packs/python/example/skillpack.yaml"
    manifest = b"id: example\nversion: 1.0.0\n"
    (root / manifest_relative).write_bytes(manifest)
    (skill_path / "SKILL.md").write_text("# Example\n", encoding="utf-8")
    git("add", "packs")
    git("commit", "-q", "-m", "published")
    source_sha = git("rev-parse", "HEAD")
    source_tree = git("rev-parse", f"{source_sha}^{{tree}}")
    manifest_blob = git("rev-parse", f"{source_sha}:{manifest_relative}")
    pack = SimpleNamespace(
        id="example",
        source_sha=source_sha,
        relative_path="packs/python/example",
    )
    pristine_state = generate._released_pack_input_state(root, pack)

    (root / manifest_relative).write_text("id: replacement\nversion: 9.9.9\n", encoding="utf-8")
    git("add", manifest_relative)
    git("commit", "-q", "-m", "replacement")
    replacement_sha = git("rev-parse", "HEAD")
    git("replace", source_sha, replacement_sha)
    graft_path = Path(git("rev-parse", "--path-format=absolute", "--git-path", "info/grafts"))
    graft_path.parent.mkdir(parents=True, exist_ok=True)
    graft_path.write_text(f"{source_sha}\n", encoding="ascii")

    assert generate._released_pack_input_state(root, pack) == pristine_state
    assert generate._git_object(root, source_sha, manifest_relative) == manifest
    assert (
        f"@git/example/{source_sha}/tree",
        source_tree,
        "git:tree",
    ) in pristine_state
    assert any(
        record[0].endswith(f"/{manifest_relative}")
        and record[1] == manifest_blob
        and record[2] == "git:blob:100644"
        for record in pristine_state
    )


def test_reconciliation_rejects_concurrent_canonical_input_edit(
    generated_repo_copy: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    root = generated_repo_copy
    generated_output = root / ".claude-plugin" / "marketplace.json"
    generated_output.write_bytes(b"stale\n")
    canonical_input = root / "evals" / "routing-boundaries.json"
    original_atomic_write = generate.safe_atomic_write_bytes
    mutated = False

    def write_then_mutate(
        path: Path,
        content: bytes,
        candidate_root: Path,
        *,
        mode: int,
        expected: object,
    ) -> None:
        nonlocal mutated
        original_atomic_write(
            path,
            content,
            candidate_root,
            mode=mode,
            expected=expected,
        )
        if not mutated:
            mutated = True
            canonical_input.write_bytes(canonical_input.read_bytes() + b"\n")

    monkeypatch.setattr(generate, "safe_atomic_write_bytes", write_then_mutate)
    with pytest.raises(SkillpackError, match="inputs changed during generated-file reconciliation"):
        generate.apply_generated_files(root)
    assert mutated


def test_reconciliation_does_not_overwrite_concurrently_changed_generated_input(
    generated_repo_copy: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    root = generated_repo_copy
    generated_output = root / ".claude-plugin" / "marketplace.json"
    generated_output.write_bytes(b"stale\n")
    readme = root / "README.md"
    readme.write_text(
        readme.read_text(encoding="utf-8").replace(
            "No stable releases are currently published.",
            "stale generated catalog",
        ),
        encoding="utf-8",
    )
    original_atomic_write = generate.safe_atomic_write_bytes
    concurrent = "concurrent maintainer edit"
    mutated = False

    def write_then_mutate(
        path: Path,
        content: bytes,
        candidate_root: Path,
        *,
        mode: int,
        expected: object,
    ) -> None:
        nonlocal mutated
        original_atomic_write(
            path,
            content,
            candidate_root,
            mode=mode,
            expected=expected,
        )
        if not mutated:
            mutated = True
            readme.write_text(
                readme.read_text(encoding="utf-8") + f"\n{concurrent}\n",
                encoding="utf-8",
            )

    monkeypatch.setattr(generate, "safe_atomic_write_bytes", write_then_mutate)
    with pytest.raises(SkillpackError):
        generate.apply_generated_files(root)
    assert mutated
    assert concurrent in readme.read_text(encoding="utf-8")


def test_reconciliation_preserves_post_build_input_identities(
    generated_repo_copy: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    root = generated_repo_copy
    generated_output = root / ".claude-plugin" / "marketplace.json"
    generated_output.write_bytes(b"stale\n")
    canonical_input = root / "schemas" / "routing-boundaries.schema.json"
    original_atomic_write = generate.safe_atomic_write_bytes
    replaced = False

    def write_then_replace(
        path: Path,
        content: bytes,
        candidate_root: Path,
        *,
        mode: int,
        expected: object,
    ) -> None:
        nonlocal replaced
        original_atomic_write(
            path,
            content,
            candidate_root,
            mode=mode,
            expected=expected,
        )
        if not replaced:
            replaced = True
            replacement = canonical_input.with_suffix(".replacement")
            replacement.write_bytes(canonical_input.read_bytes())
            os.chmod(replacement, canonical_input.stat().st_mode)
            replacement.replace(canonical_input)

    monkeypatch.setattr(generate, "safe_atomic_write_bytes", write_then_replace)
    with pytest.raises(SkillpackError, match="input identity changed during reconciliation"):
        generate.apply_generated_files(root)
    assert replaced


def test_output_records_reverify_supplied_snapshot_inputs(
    generated_repo_copy: Path,
    bound_snapshot: generate.GeneratedFiles,
) -> None:
    root = generated_repo_copy
    boundary = root / "evals" / "routing-boundaries.json"
    boundary.write_bytes(boundary.read_bytes() + b"\n")

    with pytest.raises(SkillpackError, match="snapshot inputs changed"):
        _generated_output_records(root, bound_snapshot)


def test_output_records_reject_snapshot_from_another_root(
    bound_snapshot: generate.GeneratedFiles,
    tmp_path: Path,
) -> None:
    with pytest.raises(SkillpackError, match="not bound to this repository"):
        _generated_output_records(tmp_path, bound_snapshot)
