from __future__ import annotations

import os
import subprocess
from pathlib import Path

from .models import Pack, RepositoryConfig, discover_packs, load_repository
from .path_safety import (
    inspect_path,
    read_regular_bytes,
    read_regular_text,
    remove_empty_directory,
    repository_relative,
    runtime_resource_is_allowed,
    safe_atomic_write_bytes,
    same_identity,
    unlink_regular,
    verify_preimage,
    walk_tree,
)
from .util import (
    SkillpackError,
    json_text,
    parse_skill_markdown_text,
    replace_marked_section,
    sha256_bytes,
)

GENERATED_BEGIN = "<!-- BEGIN GENERATED PACK CATALOG -->"
GENERATED_END = "<!-- END GENERATED PACK CATALOG -->"
PACK_INSTALL_BEGIN = "<!-- BEGIN GENERATED INSTALL COMMANDS -->"
PACK_INSTALL_END = "<!-- END GENERATED INSTALL COMMANDS -->"

GeneratedContent = str | bytes


class GeneratedFiles(dict[str, GeneratedContent]):
    """Generated bytes plus the intended portable mode for every destination."""

    def __init__(self) -> None:
        super().__init__()
        self.modes: dict[str, int] = {}

    def add(self, path: str, content: GeneratedContent, *, mode: int = 0o644) -> None:
        self[path] = content
        self.modes[path] = mode


def _as_bytes(content: GeneratedContent) -> bytes:
    return content if isinstance(content, bytes) else content.encode("utf-8")


def _source(config: RepositoryConfig, pack: Pack, *, codex: bool = False) -> str | dict[str, str]:
    # A local path is intentionally used until a release commit is recorded.  Publishing
    # a tag-shaped remote source before that tag exists makes generated install commands
    # look usable when they are not.
    if not pack.source_sha:
        return f"./{pack.relative_path}"
    source: dict[str, str] = {
        "source": "git-subdir",
        "url": config.git_url,
        "path": f"./{pack.relative_path}" if codex else pack.relative_path,
        "ref": pack.tag,
    }
    if pack.source_sha:
        source["sha"] = pack.source_sha
    return source


def _claude_plugin(config: RepositoryConfig, pack: Pack) -> dict:
    author = {"name": config.publisher_name}
    if config.security_email:
        author["email"] = config.security_email
    return {
        "$schema": "https://json.schemastore.org/claude-code-plugin-manifest.json",
        "name": pack.id,
        "displayName": pack.display_name,
        "version": pack.version,
        "description": pack.description,
        "author": author,
        "homepage": f"{config.web_url}/tree/{pack.source_sha or config.default_branch}/{pack.relative_path}",
        "repository": config.web_url,
        "license": pack.license,
        "keywords": pack.keywords,
    }


def _codex_plugin(config: RepositoryConfig, pack: Pack) -> dict:
    author = {
        "name": config.publisher_name,
        "url": config.web_url,
    }
    if config.security_email:
        author["email"] = config.security_email
    return {
        "name": pack.id,
        "version": pack.version,
        "description": pack.description,
        "author": author,
        "homepage": f"{config.web_url}/tree/{pack.source_sha or config.default_branch}/{pack.relative_path}",
        "repository": config.web_url,
        "license": pack.license,
        "keywords": pack.keywords,
        "skills": "./skills/",
        "interface": {
            "displayName": pack.display_name,
            "shortDescription": pack.description[:120],
            "longDescription": pack.description,
            "developerName": config.publisher_name,
            "category": pack.category,
            "capabilities": ["Read", "Write"],
            "websiteURL": f"{config.web_url}/tree/{pack.source_sha or config.default_branch}/{pack.relative_path}",
            "defaultPrompt": [
                f"Use {pack.display_name} to review the relevant files and propose a verified plan."
            ],
        },
    }


def _claude_marketplace(config: RepositoryConfig, packs: list[Pack]) -> dict:
    owner = {"name": config.publisher_name}
    if config.security_email:
        owner["email"] = config.security_email
    return {
        "name": config.marketplace_name,
        "owner": owner,
        "description": config.marketplace_description,
        "plugins": [
            {
                "name": pack.id,
                "source": _source(config, pack),
                "description": pack.description,
                "version": pack.version,
                "author": {"name": config.publisher_name},
                "category": pack.category,
                "tags": pack.keywords,
                "strict": True,
            }
            for pack in packs
            if "claude-code" in pack.targets
        ],
    }


def _codex_marketplace(config: RepositoryConfig, packs: list[Pack]) -> dict:
    return {
        "name": config.marketplace_name,
        "interface": {"displayName": config.marketplace_display_name},
        "plugins": [
            {
                "name": pack.id,
                "source": _source(config, pack, codex=True),
                "policy": {
                    "installation": "AVAILABLE",
                    "authentication": "ON_INSTALL",
                },
                "category": pack.category,
            }
            for pack in packs
            if "codex" in pack.targets
        ],
    }


def _catalog(config: RepositoryConfig, packs: list[Pack]) -> dict:
    return {
        "schemaVersion": 1,
        "project": config.project_name,
        "repository": config.slug,
        "marketplace": config.marketplace_name,
        "packs": [
            {
                "id": pack.id,
                "displayName": pack.display_name,
                "description": pack.description,
                "language": pack.language,
                "subject": pack.subject,
                "version": pack.version,
                "tag": pack.tag,
                "path": pack.relative_path,
                "license": pack.license,
                "skills": pack.skills,
                "targets": pack.targets,
                "category": pack.category,
                "keywords": pack.keywords,
                "compatibility": pack.compatibility,
                "operations": pack.operations,
                "publication": {
                    "state": pack.publication_state,
                    "sourceType": "git-subdir" if pack.source_sha else "repo-local",
                    **({"sourceSha": pack.source_sha} if pack.source_sha else {}),
                },
            }
            for pack in packs
        ],
    }


def _pack_is_stable(pack: Pack) -> bool:
    for skill in pack.skills:
        skill_path = pack.path / "skills" / skill / "SKILL.md"
        metadata, _ = parse_skill_markdown_text(
            read_regular_text(skill_path, pack.root),
            skill_path.relative_to(pack.root),
        )
        if metadata.get("metadata", {}).get("maturity") != "stable":
            return False
    return True


def _root_catalog_markdown(config: RepositoryConfig, packs: list[Pack]) -> str:
    rows = [
        "| Pack | Purpose | Skills | Version | Publication | Claude | Codex | OpenCode |",
        "|---|---|---:|---:|---|---|---|---|",
    ]
    for pack in packs:
        publication = (
            "Published"
            if pack.source_sha
            else "Awaiting source pin"
            if _pack_is_stable(pack)
            else "Release candidate"
        )
        rows.append(
            "| "
            f"[`{pack.id}`]({pack.relative_path}/README.md) | "
            f"{pack.description} | {len(pack.skills)} | `{pack.version}` | "
            f"{publication} | "
            f"{'Plugin' if 'claude-code' in pack.targets else '—'} | "
            f"{'Plugin' if 'codex' in pack.targets else '—'} | "
            f"{'Installer + HTTP catalog' if 'opencode' in pack.targets else '—'} |"
        )
    rows.extend(
        [
            "",
            f"Marketplace: `{config.marketplace_name}`. Published sources pin both the "
            "pack-specific tag and its full release commit SHA; release candidates use "
            "repository-local paths.",
        ]
    )
    return "\n".join(rows)


def _pack_install_markdown(config: RepositoryConfig, pack: Pack) -> str:
    if pack.source_sha:
        marketplace_source = config.slug
        status = (
            f"Published as `{pack.tag}` and pinned to `{pack.source_sha}` in generated "
            "marketplaces."
        )
    else:
        marketplace_source = "."
        status = (
            "The marketplace source is repository-local and unpublished. Clone this "
            "repository and run these commands from its root; remote marketplace installation "
            "remains unavailable until the post-release source-SHA update. Run strict repository "
            "validation immediately before a local install so ignored cache files are not copied."
        )
    lines = [status, ""]

    if "claude-code" in pack.targets:
        lines.extend(
            [
                "### Claude Code",
                "",
                "```bash",
                f"claude plugin marketplace add {marketplace_source}",
                f"claude plugin install {pack.id}@{config.marketplace_name}",
                "```",
                "",
            ]
        )
        if pack.source_sha:
            lines.extend(
                [
                    "Update the remote marketplace before installing an updated pack:",
                    "",
                    "```bash",
                    f"claude plugin marketplace update {config.marketplace_name}",
                    f"claude plugin update {pack.id}@{config.marketplace_name}",
                    "```",
                ]
            )
        else:
            lines.extend(
                [
                    "For local changes, regenerate this repository and reinstall the plugin:",
                    "",
                    "```bash",
                    f"claude plugin uninstall {pack.id}@{config.marketplace_name}",
                    f"claude plugin install {pack.id}@{config.marketplace_name}",
                    "```",
                ]
            )
        lines.extend(
            [
                "",
                "Uninstall:",
                "",
                "```bash",
                f"claude plugin uninstall {pack.id}@{config.marketplace_name}",
                "```",
                "",
            ]
        )

    if "codex" in pack.targets:
        lines.extend(
            [
                "### Codex",
                "",
                "```bash",
                f"codex plugin marketplace add {marketplace_source}",
                f"codex plugin add {pack.id}@{config.marketplace_name}",
                "```",
                "",
            ]
        )
        if pack.source_sha:
            lines.extend(
                [
                    "Update by refreshing the remote marketplace and reinstalling the plugin:",
                    "",
                    "```bash",
                    f"codex plugin marketplace upgrade {config.marketplace_name}",
                    f"codex plugin remove {pack.id}@{config.marketplace_name}",
                    f"codex plugin add {pack.id}@{config.marketplace_name}",
                    "```",
                ]
            )
        else:
            lines.extend(
                [
                    "For local changes, regenerate this repository and reinstall the plugin:",
                    "",
                    "```bash",
                    f"codex plugin remove {pack.id}@{config.marketplace_name}",
                    f"codex plugin add {pack.id}@{config.marketplace_name}",
                    "```",
                ]
            )
        lines.extend(
            [
                "",
                "Uninstall:",
                "",
                "```bash",
                f"codex plugin remove {pack.id}@{config.marketplace_name}",
                "```",
                "",
            ]
        )

    if "opencode" in pack.targets:
        lines.extend(
            [
                "### OpenCode or optional direct install",
                "",
                (
                    "The direct installer uses the public-preview `gh skill` interface. It "
                    "checks the installed CLI before making changes; `--dry-run`/`-DryRun` "
                    "does not require or probe `gh`."
                ),
                "",
            ]
        )
        if pack.source_sha:
            lines.extend(
                [
                    "```bash",
                    (
                        f"bash dist/install/{pack.id}.sh --repository {config.slug} "
                        f"--agent opencode --scope user --pin {pack.source_sha}"
                    ),
                    "```",
                    "",
                    "PowerShell:",
                    "",
                    "```powershell",
                    (
                        f".\\dist\\install\\{pack.id}.ps1 -Repository {config.slug} "
                        f"-Agent opencode -Scope user -Pin {pack.source_sha}"
                    ),
                    "```",
                    "",
                    f"The immutable default pin is `{pack.source_sha}`.",
                ]
            )
        else:
            lines.extend(
                [
                    (
                        "No executable remote install command is published before a release "
                        "SHA is recorded. Inspect the future exact-path operations locally:"
                    ),
                    "",
                    "```bash",
                    f"bash dist/install/{pack.id}.sh --dry-run",
                    "```",
                    "",
                    "```powershell",
                    f".\\dist\\install\\{pack.id}.ps1 -DryRun",
                    "```",
                    "",
                    "The dry run does not install skills or make a compatibility claim.",
                ]
            )

    return "\n".join(lines).rstrip()


def _bash_installer(config: RepositoryConfig, pack: Pack) -> str:
    skills = "\n".join(f'  "{skill}"' for skill in pack.skills)
    default_pin = pack.source_sha or "UNPUBLISHED"
    unpublished = 0 if pack.source_sha else 1
    return f"""#!/usr/bin/env bash
# Generated by tools/generate-installers. Do not edit by hand.
set -euo pipefail

repository="${{GENAPTIC_SKILLSETS_REPOSITORY:-{config.slug}}}"
agent="opencode"
scope="user"
pin="${{GENAPTIC_SKILLSETS_REF:-{default_pin}}}"
force=0
dry_run=0
unpublished={unpublished}

usage() {{
  cat <<'EOF'
Install the {pack.display_name} skillpack with GitHub CLI.

Usage:
  {pack.id}.sh [options]

Options:
  --repository ORG/PROJECT  Source repository.
  --agent AGENT             Target agent (default: opencode).
  --scope SCOPE             user or project (default: user).
  --pin REF                 Pack tag or full commit SHA.
  --force                   Overwrite installed skills.
  --dry-run                 Print commands without executing them.
  -h, --help                Show this help.

The installer invokes only the public-preview `gh skill install` interface. It checks both
`gh skill --help` and `gh skill install --help` before making changes. Dry runs do not require
or probe `gh`. Every probe and install invocation sets `GH_TELEMETRY=false`,
`GH_PROMPT_DISABLED=1`, and `GH_NO_UPDATE_NOTIFIER=1` for that invocation only. The installer
does not execute bundled skill scripts.
EOF
}}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repository) repository="${{2:?missing value for --repository}}"; shift 2 ;;
    --agent) agent="${{2:?missing value for --agent}}"; shift 2 ;;
    --scope) scope="${{2:?missing value for --scope}}"; shift 2 ;;
    --pin) pin="${{2:?missing value for --pin}}"; shift 2 ;;
    --force) force=1; shift ;;
    --dry-run) dry_run=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

[[ "$repository" =~ ^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$ ]] || {{
  echo "--repository must use ORG/PROJECT format." >&2
  exit 2
}}
[[ "$scope" == "user" || "$scope" == "project" ]] || {{
  echo "--scope must be user or project." >&2
  exit 2
}}
[[ -n "$agent" && "$agent" != -* ]] || {{
  echo "--agent must be a non-empty agent identifier." >&2
  exit 2
}}
[[ -n "$pin" && "$pin" != -* ]] || {{
  echo "--pin must be a tag or full commit SHA." >&2
  exit 2
}}
[[ "$dry_run" -eq 1 || "$pin" != "UNPUBLISHED" ]] || {{
  echo "This pack is unpublished; pass --pin with a reviewed full commit SHA." >&2
  exit 2
}}
if [[ "$dry_run" -eq 0 && "$unpublished" -eq 1 && ! "$pin" =~ ^[0-9a-fA-F]{{40}}$ ]]; then
  echo "Unpublished packs require --pin with a full 40-character commit SHA." >&2
  exit 2
fi

if [[ "$dry_run" -eq 0 ]]; then
  if ! command -v gh >/dev/null 2>&1; then
    echo "GitHub CLI (gh) is not installed; the optional direct installer is unavailable." >&2
    exit 127
  fi
  if ! GH_TELEMETRY=false GH_PROMPT_DISABLED=1 GH_NO_UPDATE_NOTIFIER=1 gh skill --help >/dev/null 2>&1; then
    echo "Installed GitHub CLI does not support the public-preview 'gh skill' command." >&2
    exit 1
  fi
  if ! GH_TELEMETRY=false GH_PROMPT_DISABLED=1 GH_NO_UPDATE_NOTIFIER=1 gh skill install --help >/dev/null 2>&1; then
    echo "Installed GitHub CLI does not support the public-preview 'gh skill install' command." >&2
    exit 1
  fi
fi

skills=(
{skills}
)

for skill in "${{skills[@]}}"; do
  path="{pack.relative_path}/skills/$skill"
  command=(gh skill install "$repository" "$path" --agent "$agent" --scope "$scope" --pin "$pin")
  if [[ "$force" -eq 1 ]]; then
    command+=(--force)
  fi
  if [[ "$dry_run" -eq 1 ]]; then
    printf '%q ' "${{command[@]}}"
    printf '\\n'
  else
    printf 'Installing %s for %s at %s scope...\\n' "$skill" "$agent" "$scope"
    GH_TELEMETRY=false GH_PROMPT_DISABLED=1 GH_NO_UPDATE_NOTIFIER=1 "${{command[@]}}"
  fi
done
"""


def _powershell_installer(config: RepositoryConfig, pack: Pack) -> str:
    skills = ",\n    ".join(f'"{skill}"' for skill in pack.skills)
    default_pin = pack.source_sha or "UNPUBLISHED"
    unpublished = "$true" if not pack.source_sha else "$false"
    return f"""# Generated by tools/generate-installers. Do not edit by hand.
[CmdletBinding(SupportsShouldProcess = $true)]
param(
    [ValidatePattern('^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$')]
    [string]$Repository = $(if ($env:GENAPTIC_SKILLSETS_REPOSITORY) {{
        $env:GENAPTIC_SKILLSETS_REPOSITORY
    }} else {{
        "{config.slug}"
    }}),

    [ValidateNotNullOrEmpty()]
    [string]$Agent = "opencode",

    [ValidateSet("user", "project")]
    [string]$Scope = "user",

    [ValidateNotNullOrEmpty()]
    [string]$Pin = $(if ($env:GENAPTIC_SKILLSETS_REF) {{
        $env:GENAPTIC_SKILLSETS_REF
    }} else {{
        "{default_pin}"
    }}),

    [switch]$Force,
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"
$Unpublished = {unpublished}

if (-not $DryRun -and $Pin -eq "UNPUBLISHED") {{
    throw "This pack is unpublished; pass -Pin with a reviewed full commit SHA."
}}
if (-not $DryRun -and $Unpublished -and $Pin -notmatch '^[0-9a-fA-F]{{40}}$') {{
    throw "Unpublished packs require -Pin with a full 40-character commit SHA."
}}

$GhCommand = $null
if (-not $DryRun) {{
    $GhCommand = @(Get-Command gh -CommandType Application -ErrorAction SilentlyContinue)[0]
    if (-not $GhCommand) {{
        Write-Error -Message (
            "GitHub CLI (gh) is not installed; the optional direct installer is unavailable."
        ) -ErrorAction Continue
        exit 127
    }}
}}

$skills = @(
    {skills}
)

$GhEnvironment = [ordered]@{{
    "GH_TELEMETRY" = "false"
    "GH_PROMPT_DISABLED" = "1"
    "GH_NO_UPDATE_NOTIFIER" = "1"
}}
$GhEnvironmentSnapshot = @{{}}

if (-not $DryRun) {{
    foreach ($name in $GhEnvironment.Keys) {{
        $entry = Get-Item -LiteralPath "Env:$name" -ErrorAction SilentlyContinue
        $GhEnvironmentSnapshot[$name] = [pscustomobject]@{{
            Present = $null -ne $entry
            Value = if ($null -ne $entry) {{ $entry.Value }} else {{ $null }}
        }}
    }}
}}

try {{
    if (-not $DryRun) {{
        foreach ($name in $GhEnvironment.Keys) {{
            Set-Item -LiteralPath "Env:$name" -Value $GhEnvironment[$name]
        }}

        & $GhCommand.Source "skill" "--help" *> $null
        if ($LASTEXITCODE -ne 0) {{
            throw "Installed GitHub CLI does not support the public-preview 'gh skill' command."
        }}
        & $GhCommand.Source "skill" "install" "--help" *> $null
        if ($LASTEXITCODE -ne 0) {{
            throw (
                "Installed GitHub CLI does not support the public-preview " +
                "'gh skill install' command."
            )
        }}
    }}

foreach ($skill in $skills) {{
    $path = "{pack.relative_path}/skills/$skill"
    $arguments = @(
        "skill", "install", $Repository, $path,
        "--agent", $Agent,
        "--scope", $Scope,
        "--pin", $Pin
    )
    if ($Force) {{
        $arguments += "--force"
    }}

    $display = "gh " + ($arguments | ForEach-Object {{
        if ($_ -match '[\\s"]') {{ '"' + ($_ -replace '"', '\\"') + '"' }} else {{ $_ }}
    }} ) -join " "

    if ($DryRun) {{
        Write-Output $display
        continue
    }}

    if ($PSCmdlet.ShouldProcess("$skill for $Agent at $Scope scope", $display)) {{
        & $GhCommand.Source @arguments
        if ($LASTEXITCODE -ne 0) {{
            throw "gh skill install failed for $skill with exit code $LASTEXITCODE."
        }}
    }}
}}
}} finally {{
    if (-not $DryRun) {{
        foreach ($name in $GhEnvironment.Keys) {{
            $snapshot = $GhEnvironmentSnapshot[$name]
            if ($snapshot.Present) {{
                Set-Item -LiteralPath "Env:$name" -Value $snapshot.Value
            }} else {{
                Remove-Item -LiteralPath "Env:$name" -ErrorAction SilentlyContinue
            }}
        }}
    }}
}}
"""


def _installer_readme(config: RepositoryConfig, packs: list[Pack]) -> str:
    lines = [
        "# Generated direct installers",
        "",
        "These optional adapters are generated from `skillpack.yaml`. They install each declared",
        "skill by exact path with the public-preview `gh skill install` interface and require an",
        "immutable full commit SHA.",
        "",
        "They probe both `gh skill --help` and `gh skill install --help` before changing files.",
        "A missing or unsupported command is reported as unavailable; it is never a compatibility",
        "pass. Dry runs neither require nor probe `gh`.",
        "",
        "Each probe and install invocation sets `GH_TELEMETRY=false`, `GH_PROMPT_DISABLED=1`,",
        "and `GH_NO_UPDATE_NOTIFIER=1` in its process environment. PowerShell restores any prior",
        "values after the transaction. These controls do not imply broader network isolation.",
        "",
        "The installers do not run bundled helper scripts. Review a dry run before execution.",
        "",
        "| Pack | Bash | PowerShell | Publication / default pin |",
        "|---|---|---|---|",
    ]
    for pack in packs:
        lines.append(
            f"| `{pack.id}` | `{pack.id}.sh` | `{pack.id}.ps1` | "
            f"`{pack.source_sha or 'unpublished; explicit SHA required'}` |"
        )
    lines.extend(
        [
            "",
            f"Default repository: `{config.slug}`.",
            "",
            "Review generated commands and the release before using `--force`.",
        ]
    )
    return "\n".join(lines) + "\n"


def _opencode_readme(packs: list[Pack]) -> str:
    lines = [
        "# Generated OpenCode V2 catalogs",
        "",
        "Each language/subject directory is an independently hostable HTTP catalog. Serve the",
        "directory containing `index.json` as the catalog base URL.",
        "",
        "The named skill Markdown and resources are generated copies of canonical pack content.",
        "Do not edit this directory by hand.",
        "",
        "| Pack | Catalog path | Version |",
        "|---|---|---|",
    ]
    for pack in packs:
        lines.append(
            f"| `{pack.id}` | `{pack.language}/{pack.subject}/index.json` | `{pack.version}` |"
        )
    return "\n".join(lines) + "\n"


def _is_runtime_file(path: Path, skill_dir: Path) -> bool:
    relative = path.relative_to(skill_dir)
    return runtime_resource_is_allowed(relative)


def _runtime_files(root: Path, skill_dir: Path) -> list[Path]:
    paths: list[Path] = []
    for subdir in ("references", "assets", "scripts"):
        folder = skill_dir / subdir
        snapshot = walk_tree(folder, root, allow_missing=True)
        paths.extend(
            path for path, _metadata in snapshot.files if _is_runtime_file(path, skill_dir)
        )
    return paths


def _tracked_source_modes(root: Path) -> dict[str, int]:
    """Return Git-index modes once so generation remains fast and cross-platform."""

    try:
        result = subprocess.run(
            ["git", "-C", str(root), "ls-files", "--stage", "-z"],
            check=False,
            capture_output=True,
            text=True,
        )
    except OSError:
        return {}
    if result.returncode != 0:
        return {}
    modes: dict[str, int] = {}
    for entry in result.stdout.split("\0"):
        if not entry or "\t" not in entry:
            continue
        metadata, relative = entry.split("\t", 1)
        index_mode = metadata.split(maxsplit=1)[0]
        modes[relative] = 0o755 if index_mode == "100755" else 0o644
    return modes


def _portable_source_mode(
    root: Path, path: Path, tracked_modes: dict[str, int] | None = None
) -> int:
    """Read the tracked executable bit portably, falling back to filesystem mode."""

    try:
        relative = path.relative_to(root).as_posix()
    except ValueError:
        relative = ""
    modes = tracked_modes if tracked_modes is not None else _tracked_source_modes(root)
    if relative in modes:
        return modes[relative]
    metadata = inspect_path(path, root, leaf_kind="file")
    assert metadata is not None
    return 0o755 if metadata.st_mode & 0o111 else 0o644


def build_generated_files(root: Path) -> GeneratedFiles:
    root = Path(os.path.abspath(os.fspath(root)))
    config = load_repository(root)
    packs = discover_packs(root)
    if not packs:
        raise SkillpackError("No skillpack.yaml files were found under packs/*/*/.")
    tracked_modes = _tracked_source_modes(root)

    files = GeneratedFiles()
    for pack in packs:
        if "claude-code" in pack.targets:
            files.add(
                f"{pack.relative_path}/.claude-plugin/plugin.json",
                json_text(_claude_plugin(config, pack)),
            )
        if "codex" in pack.targets:
            files.add(
                f"{pack.relative_path}/.codex-plugin/plugin.json",
                json_text(_codex_plugin(config, pack)),
            )

    files.add(".claude-plugin/marketplace.json", json_text(_claude_marketplace(config, packs)))
    files.add(".agents/plugins/marketplace.json", json_text(_codex_marketplace(config, packs)))
    files.add("catalog.json", json_text(_catalog(config, packs)))

    root_readme = read_regular_text(root / "README.md", root)
    files.add(
        "README.md",
        replace_marked_section(
            root_readme, GENERATED_BEGIN, GENERATED_END, _root_catalog_markdown(config, packs)
        ),
    )

    for pack in packs:
        pack_readme_path = pack.path / "README.md"
        pack_readme_metadata = inspect_path(
            pack_readme_path,
            root,
            leaf_kind="file",
            allow_missing=True,
        )
        if pack_readme_metadata is not None:
            pack_readme = read_regular_text(pack_readme_path, root)
            files.add(
                f"{pack.relative_path}/README.md",
                replace_marked_section(
                    pack_readme,
                    PACK_INSTALL_BEGIN,
                    PACK_INSTALL_END,
                    _pack_install_markdown(config, pack),
                ),
            )

    opencode_packs = [pack for pack in packs if "opencode" in pack.targets]
    files.add("dist/install/README.md", _installer_readme(config, opencode_packs))
    files.add("dist/opencode/README.md", _opencode_readme(opencode_packs))

    for pack in opencode_packs:
        files.add(f"dist/install/{pack.id}.sh", _bash_installer(config, pack), mode=0o755)
        files.add(f"dist/install/{pack.id}.ps1", _powershell_installer(config, pack))

        catalog_base = Path("dist/opencode") / pack.language / pack.subject
        catalog_skills: list[dict] = []
        for skill in pack.skills:
            skill_dir = pack.path / "skills" / skill
            source_skill = skill_dir / "SKILL.md"
            runtime = _runtime_files(root, skill_dir)
            listed_files = [f"{skill}.md"]
            target_prefix = catalog_base / skill
            files.add(
                (target_prefix / f"{skill}.md").as_posix(),
                read_regular_bytes(source_skill, root),
            )
            for resource in runtime:
                relative = resource.relative_to(skill_dir)
                listed_files.append(relative.as_posix())
                mode = _portable_source_mode(root, resource, tracked_modes)
                files.add(
                    (target_prefix / relative).as_posix(),
                    read_regular_bytes(resource, root),
                    mode=mode,
                )
            catalog_skills.append({"name": skill, "version": pack.version, "files": listed_files})
        files.add(
            (catalog_base / "index.json").as_posix(),
            json_text({"skills": catalog_skills}),
        )

    manifest_entries = [
        {
            "path": path,
            "sha256": sha256_bytes(_as_bytes(content)),
            "size": len(_as_bytes(content)),
            "mode": f"{files.modes[path]:04o}",
        }
        for path, content in sorted(files.items())
        if path != "dist/generated-files.json"
    ]
    files.add(
        "dist/generated-files.json",
        json_text({"schemaVersion": 1, "files": manifest_entries}),
    )
    return files


def apply_generated_files(root: Path, *, check: bool = False) -> list[str]:
    root = Path(os.path.abspath(os.fspath(root)))
    canonical_before = walk_tree(root / "packs", root)
    root_source_preimages = {
        path: inspect_path(path, root, leaf_kind="file")
        for path in (root / "repository.yaml", root / "README.md")
    }
    expected = build_generated_files(root)
    changed: list[str] = []

    canonical_after = walk_tree(root / "packs", root)
    before_nodes = {
        repository_relative(path, root): metadata
        for path, metadata in (*canonical_before.directories, *canonical_before.files)
    }
    after_nodes = {
        repository_relative(path, root): metadata
        for path, metadata in (*canonical_after.directories, *canonical_after.files)
    }
    if set(before_nodes) != set(after_nodes) or any(
        not same_identity(metadata, after_nodes[path]) for path, metadata in before_nodes.items()
    ):
        raise SkillpackError("Canonical pack content changed during generation preflight.")
    for path, preimage in root_source_preimages.items():
        assert preimage is not None
        verify_preimage(path, root, preimage)

    packs = discover_packs(root)
    generated_roots = [
        root / ".claude-plugin",
        root / ".agents" / "plugins",
        root / "dist" / "install",
        root / "dist" / "opencode",
        *(pack.path / ".claude-plugin" for pack in packs),
        *(pack.path / ".codex-plugin" for pack in packs),
    ]

    expected_paths: dict[str, tuple[Path, os.stat_result | None]] = {}
    for relative in expected:
        raw_relative = Path(relative)
        if raw_relative.is_absolute() or ".." in raw_relative.parts:
            raise SkillpackError(f"Generated destination is not repository-relative: {relative!r}.")
        path = root / raw_relative
        normalized = repository_relative(path, root).as_posix()
        if normalized != raw_relative.as_posix():
            raise SkillpackError(f"Generated destination is not normalized: {relative!r}.")
        preimage = inspect_path(path, root, leaf_kind="file", allow_missing=True)
        expected_paths[relative] = (path, preimage)

    cleanup_files: dict[Path, os.stat_result] = {}
    cleanup_directories: dict[Path, os.stat_result] = {}
    for generated_root in generated_roots:
        snapshot = walk_tree(generated_root, root, allow_missing=True)
        cleanup_files.update(snapshot.files)
        cleanup_directories.update(snapshot.directories)

    for relative, content in expected.items():
        path, preimage = expected_paths[relative]
        wanted = _as_bytes(content)
        metadata = verify_preimage(path, root, preimage)
        actual = read_regular_bytes(path, root) if metadata is not None else None
        actual_mode = metadata.st_mode & 0o777 if metadata is not None else None
        expected_mode = expected.modes[relative]
        mode_mismatch = os.name != "nt" and actual_mode != expected_mode
        if actual != wanted or mode_mismatch:
            changed.append(relative)
            if not check:
                safe_atomic_write_bytes(
                    path,
                    wanted,
                    root,
                    mode=expected_mode,
                    expected=preimage,
                )

    expected_relative_paths = set(expected_paths)
    stale_files: list[tuple[Path, os.stat_result]] = []
    for path, metadata in cleanup_files.items():
        relative = repository_relative(path, root).as_posix()
        if relative not in expected_relative_paths:
            changed.append(relative)
            stale_files.append((path, metadata))

    if not check:
        for path, metadata in sorted(stale_files, key=lambda item: item[0].as_posix()):
            unlink_regular(path, root, expected=metadata)
        for directory, metadata in sorted(
            cleanup_directories.items(),
            key=lambda item: (len(item[0].parts), item[0].as_posix()),
            reverse=True,
        ):
            remove_empty_directory(directory, root, expected=metadata)

    if check and changed:
        detail = "\n".join(f"  - {path}" for path in sorted(set(changed)))
        raise SkillpackError(
            "Generated files are missing or stale. Run `python3 tools/generate-all`:\n" + detail
        )
    return sorted(set(changed))
