from __future__ import annotations

import os
import subprocess
import textwrap
from dataclasses import dataclass
from html import escape
from pathlib import Path, PurePath

import yaml

from .evals import RoutingBoundarySummary, validate_routing_boundaries
from .lifecycle import DistributionChannel, select_packs
from .models import Pack, RepositoryConfig, discover_packs, load_repository
from .path_safety import (
    inspect_path,
    read_regular_bytes,
    read_regular_text,
    remove_empty_directory,
    repository_relative,
    runtime_resource_is_allowed,
    safe_atomic_write_bytes,
    same_identity,
    unlink_regular,
    verify_preimage,
    walk_tree,
)
from .util import (
    SkillpackError,
    json_text,
    replace_marked_section,
    sha256_bytes,
)

GENERATED_BEGIN = "<!-- BEGIN GENERATED PACK CATALOG -->"
GENERATED_END = "<!-- END GENERATED PACK CATALOG -->"
PACK_INSTALL_BEGIN = "<!-- BEGIN GENERATED INSTALL COMMANDS -->"
PACK_INSTALL_END = "<!-- END GENERATED INSTALL COMMANDS -->"
PACK_LIFECYCLE_BEGIN = "<!-- BEGIN GENERATED LIFECYCLE -->"
PACK_LIFECYCLE_END = "<!-- END GENERATED LIFECYCLE -->"
BOUNDARY_MATRIX_BEGIN = "<!-- BEGIN GENERATED ROUTING BOUNDARY MATRIX -->"
BOUNDARY_MATRIX_END = "<!-- END GENERATED ROUTING BOUNDARY MATRIX -->"

GeneratedContent = str | bytes
GenerationInputRecord = tuple[str, str, str]
GenerationInputState = tuple[GenerationInputRecord, ...]


@dataclass(frozen=True)
class _GenerationInputCapture:
    """Logical generator inputs plus exact preimages held across reconciliation."""

    state: GenerationInputState
    preimages: tuple[tuple[Path, os.stat_result], ...]


class GeneratedFiles(dict[str, GeneratedContent]):
    """Generated bytes plus the intended portable mode for every destination."""

    def __init__(self) -> None:
        super().__init__()
        self.modes: dict[str, int] = {}
        self._source_root: Path | None = None
        self._source_state: GenerationInputState | None = None

    def add(self, path: str, content: GeneratedContent, *, mode: int = 0o644) -> None:
        self[path] = content
        self.modes[path] = mode


class GeneratedChanges(list[str]):
    """List-compatible reconciliation result carrying its authoritative snapshot."""

    def __init__(self, changed: list[str], generated_files: GeneratedFiles) -> None:
        super().__init__(changed)
        self.generated_files = generated_files


def _isolated_git_environment() -> dict[str, str]:
    """Return a non-interactive Git environment with no inherited Git controls."""

    environment = {
        key: value for key, value in os.environ.items() if not key.upper().startswith("GIT_")
    }
    environment.update(
        {
            "GIT_CONFIG_GLOBAL": os.devnull,
            "GIT_CONFIG_NOSYSTEM": "1",
            "GIT_LITERAL_PATHSPECS": "1",
            "GIT_LFS_SKIP_SMUDGE": "1",
            "GIT_NO_LAZY_FETCH": "1",
            "GIT_NO_REPLACE_OBJECTS": "1",
            "GIT_OPTIONAL_LOCKS": "0",
            "GIT_TERMINAL_PROMPT": "0",
        }
    )
    return environment


def _exact_git(root: Path, *arguments: str) -> subprocess.CompletedProcess[bytes]:
    """Run one local-only Git object query without replacement-object semantics."""

    try:
        return subprocess.run(
            [
                "git",
                "--no-replace-objects",
                "--no-lazy-fetch",
                "-c",
                "core.longpaths=true",
                "-c",
                "core.useReplaceRefs=false",
                "-C",
                str(root),
                *arguments,
            ],
            check=False,
            capture_output=True,
            env=_isolated_git_environment(),
        )
    except OSError as exc:
        raise SkillpackError("Git is required to render a published release snapshot.") from exc


def _require_object_id(value: str, *, label: str) -> str:
    if len(value) != 40 or any(character not in "0123456789abcdef" for character in value):
        raise SkillpackError(f"{label} must be an exact lowercase 40-character object ID.")
    return value


def _exact_commit(root: Path, source_sha: str) -> tuple[bytes, str]:
    """Read a raw commit and return its exact tree, bypassing graft ancestry."""

    source_sha = _require_object_id(source_sha, label="Published source SHA")
    completed = _exact_git(root, "cat-file", "commit", source_sha)
    if completed.returncode:
        detail = completed.stderr.decode("utf-8", errors="replace").strip()
        raise SkillpackError(
            f"Could not read published commit {source_sha}: {detail or 'missing object'}"
        )
    first_line = completed.stdout.partition(b"\n")[0]
    if not first_line.startswith(b"tree "):
        raise SkillpackError(f"Published object {source_sha} is not a canonical commit object.")
    try:
        tree_oid = first_line.removeprefix(b"tree ").decode("ascii")
    except UnicodeDecodeError as exc:
        raise SkillpackError(
            f"Published commit {source_sha} has a malformed tree object ID."
        ) from exc
    return completed.stdout, _require_object_id(
        tree_oid,
        label=f"Published commit {source_sha} tree",
    )


def _parse_tree_records(
    payload: bytes,
    *,
    label: str,
) -> list[tuple[str, str, str, str]]:
    """Parse NUL-delimited ls-tree records as path, mode, kind, and exact object ID."""

    entries: list[tuple[str, str, str, str]] = []
    for record in payload.split(b"\0"):
        if not record:
            continue
        try:
            metadata, raw_path = record.split(b"\t", 1)
            mode, kind, object_id = metadata.decode("ascii").split(" ", 2)
            relative = raw_path.decode("utf-8")
        except (UnicodeDecodeError, ValueError) as exc:
            raise SkillpackError(f"{label}: malformed released Git tree entry.") from exc
        if kind not in {"blob", "tree"}:
            raise SkillpackError(f"{label}: unsupported released Git object kind {kind!r}.")
        entries.append(
            (
                relative,
                mode,
                kind,
                _require_object_id(object_id, label=f"{label} object"),
            )
        )
    return entries


def _released_pack_input_state(root: Path, pack: Pack) -> GenerationInputState:
    """Fingerprint exact immutable objects used to generate one published pack."""

    source_sha = pack.source_sha
    if not source_sha:
        raise SkillpackError(f"{pack.id}: published generation requires a source SHA.")
    commit, tree_oid = _exact_commit(root, source_sha)
    completed = _exact_git(
        root,
        "ls-tree",
        "-r",
        "-t",
        "-z",
        "--full-tree",
        tree_oid,
        "--",
        pack.relative_path,
    )
    if completed.returncode:
        detail = completed.stderr.decode("utf-8", errors="replace").strip()
        raise SkillpackError(
            f"Could not enumerate released objects for {pack.id}: {detail or 'missing object'}"
        )
    prefix = f"@git/{pack.id}/{source_sha}"
    records: list[GenerationInputRecord] = [
        (f"{prefix}/commit", source_sha, f"git:commit:{sha256_bytes(commit)}"),
        (f"{prefix}/tree", tree_oid, "git:tree"),
    ]
    pack_prefix = f"{pack.relative_path}/"
    pack_tree_found = False
    for relative, mode, kind, object_id in _parse_tree_records(
        completed.stdout,
        label=f"{pack.id} released tree",
    ):
        if relative == pack.relative_path:
            pack_tree_found = kind == "tree"
        elif not relative.startswith(pack_prefix):
            continue
        records.append((f"{prefix}/{relative}", object_id, f"git:{kind}:{mode}"))
    if not pack_tree_found:
        raise SkillpackError(f"{pack.id}: released source has no exact pack tree.")
    return tuple(sorted(records))


def _capture_generation_inputs(root: Path) -> _GenerationInputCapture:
    """Fingerprint every mutable and immutable input affecting generated bytes."""

    candidates: dict[Path, os.stat_result] = {}
    for path in (
        root / "repository.yaml",
        root / "README.md",
        root / "docs" / "evals.md",
        root / "evals" / "routing-boundaries.json",
        root / "schemas" / "routing-boundaries.schema.json",
    ):
        metadata = inspect_path(path, root, leaf_kind="file")
        assert metadata is not None
        candidates[path] = metadata
    pack_snapshot = walk_tree(root / "packs", root)
    for path, metadata in pack_snapshot.files:
        relative_to_packs = path.relative_to(root / "packs")
        if any(part in {".claude-plugin", ".codex-plugin"} for part in relative_to_packs.parts):
            continue
        candidates[path] = metadata

    tracked_modes = _tracked_source_modes(root)
    records: list[GenerationInputRecord] = []
    for path in sorted(candidates, key=lambda item: repository_relative(item, root).as_posix()):
        relative = repository_relative(path, root).as_posix()
        metadata = candidates[path]
        content = read_regular_bytes(path, root, expected=metadata)
        mode = tracked_modes.get(relative)
        mode_record = (
            f"tracked:{mode:04o}"
            if mode is not None
            else f"filesystem:{metadata.st_mode & 0o777:04o}"
        )
        records.append((relative, sha256_bytes(content), mode_record))
    packs = discover_packs(root)
    for pack in select_packs(packs, "public"):
        records.extend(_released_pack_input_state(root, pack))
    return _GenerationInputCapture(
        state=tuple(sorted(records)),
        preimages=tuple(
            sorted(
                candidates.items(),
                key=lambda item: repository_relative(item[0], root).as_posix(),
            )
        ),
    )


def _generation_input_state(root: Path) -> GenerationInputState:
    return _capture_generation_inputs(root).state


def _bind_generation_snapshot(
    root: Path,
    generated: GeneratedFiles,
    source_state: GenerationInputState | None = None,
) -> None:
    generated._source_root = root
    generated._source_state = (
        source_state if source_state is not None else _generation_input_state(root)
    )


def _verify_generation_snapshot(
    root: Path,
    generated: GeneratedFiles,
    source_state: GenerationInputState | None = None,
) -> None:
    if generated._source_root != root or generated._source_state is None:
        raise SkillpackError("Generated snapshot is not bound to this repository checkout.")
    current_state = source_state if source_state is not None else _generation_input_state(root)
    if current_state != generated._source_state:
        raise SkillpackError(
            "Generated snapshot inputs changed; rebuild generated files before validation."
        )


def _expected_post_reconciliation_state(
    source_state: GenerationInputState,
    generated: GeneratedFiles,
) -> GenerationInputState:
    """Derive intended post-write input state without trusting post-write source bytes."""

    records = {relative: (digest, mode) for relative, digest, mode in source_state}
    for relative in records.keys() & generated.keys():
        digest = sha256_bytes(_as_bytes(generated[relative]))
        _old_digest, mode = records[relative]
        if mode.startswith("filesystem:"):
            mode = f"filesystem:{generated.modes[relative]:04o}"
        records[relative] = (digest, mode)
    return tuple((relative, digest, mode) for relative, (digest, mode) in sorted(records.items()))


def _as_bytes(content: GeneratedContent) -> bytes:
    return content if isinstance(content, bytes) else content.encode("utf-8")


def _channel_version(pack: Pack, channel: DistributionChannel) -> str:
    if channel == "public":
        if not pack.published_version:
            raise SkillpackError(f"{pack.id}: public generation requires latest-release.")
        return pack.published_version
    return pack.version


def _channel_tag(pack: Pack, channel: DistributionChannel) -> str:
    return f"{pack.id}-v{_channel_version(pack, channel)}"


def _channel_source_sha(pack: Pack, channel: DistributionChannel) -> str | None:
    return pack.source_sha if channel == "public" else None


def _git_object(root: Path, revision: str, relative: str) -> bytes:
    """Read one immutable Git blob without checking out or executing tree content."""

    _commit, tree_oid = _exact_commit(root, revision)
    completed = _exact_git(
        root,
        "ls-tree",
        "-z",
        "--full-tree",
        tree_oid,
        "--",
        relative,
    )
    if completed.returncode:
        detail = completed.stderr.decode("utf-8", errors="replace").strip()
        raise SkillpackError(
            f"Could not read published blob {revision}:{relative}: {detail or 'missing object'}"
        )
    entries = _parse_tree_records(
        completed.stdout,
        label=f"Published blob {revision}:{relative}",
    )
    matching = [entry for entry in entries if entry[0] == relative]
    if (
        len(matching) != 1
        or matching[0][2] != "blob"
        or matching[0][1]
        not in {
            "100644",
            "100755",
        }
    ):
        raise SkillpackError(
            f"Published path {revision}:{relative} is not one exact regular-file blob."
        )
    return _git_blob(root, matching[0][3], label=f"Published blob {revision}:{relative}")


def _git_blob(root: Path, object_id: str, *, label: str) -> bytes:
    object_id = _require_object_id(object_id, label=f"{label} object")
    completed = _exact_git(root, "cat-file", "blob", object_id)
    if completed.returncode:
        detail = completed.stderr.decode("utf-8", errors="replace").strip()
        raise SkillpackError(f"Could not read {label}: {detail or 'missing object'}")
    return completed.stdout


def _published_snapshot(root: Path, pack: Pack) -> Pack:
    """Load public metadata from the exact released tree, then attach current publication state."""

    source_sha = pack.source_sha
    version = pack.published_version
    if not source_sha or not version or pack.latest_release is None:
        raise SkillpackError(f"{pack.id}: public generation requires a complete latest-release.")
    relative = f"{pack.relative_path}/skillpack.yaml"
    try:
        raw = yaml.safe_load(_git_object(root, source_sha, relative).decode("utf-8"))
    except (UnicodeDecodeError, yaml.YAMLError) as exc:
        raise SkillpackError(
            f"{pack.id}: released skillpack manifest is not valid UTF-8 YAML."
        ) from exc
    if not isinstance(raw, dict):
        raise SkillpackError(f"{pack.id}: released skillpack manifest must be a mapping.")
    if raw.get("id") != pack.id or raw.get("version") != version:
        raise SkillpackError(
            f"{pack.id}: latest-release does not match the manifest at {source_sha}."
        )
    raw["publication"] = dict(pack.raw["publication"])
    raw["distribution"] = dict(pack.raw["distribution"])
    return Pack(root=pack.root, path=pack.path, raw=raw)


def _source(
    config: RepositoryConfig,
    pack: Pack,
    *,
    channel: DistributionChannel,
    codex: bool = False,
    local_path: str | None = None,
) -> str | dict[str, str]:
    if channel != "public":
        return local_path or f"./{pack.relative_path}"
    source_sha = _channel_source_sha(pack, channel)
    if not source_sha:
        raise SkillpackError(f"{pack.id}: public source requires an exact release SHA.")
    source: dict[str, str] = {
        "source": "git-subdir",
        "url": config.git_url,
        "path": f"./{pack.relative_path}" if codex else pack.relative_path,
        "ref": _channel_tag(pack, channel),
        "sha": source_sha,
    }
    return source


def _claude_plugin(
    config: RepositoryConfig, pack: Pack, channel: DistributionChannel = "development"
) -> dict:
    author = {"name": config.publisher_name}
    if config.security_email:
        author["email"] = config.security_email
    return {
        "$schema": "https://json.schemastore.org/claude-code-plugin-manifest.json",
        "name": pack.id,
        "displayName": pack.display_name,
        "version": _channel_version(pack, channel),
        "description": pack.short_description,
        "author": author,
        "homepage": (
            f"{config.web_url}/tree/"
            f"{_channel_source_sha(pack, channel) or config.default_branch}/{pack.relative_path}"
        ),
        "repository": config.web_url,
        "license": pack.license,
        "keywords": pack.keywords,
    }


def _codex_plugin(
    config: RepositoryConfig, pack: Pack, channel: DistributionChannel = "development"
) -> dict:
    author = {
        "name": config.publisher_name,
        "url": config.web_url,
    }
    if config.security_email:
        author["email"] = config.security_email
    return {
        "name": pack.id,
        "version": _channel_version(pack, channel),
        "description": pack.description,
        "author": author,
        "homepage": (
            f"{config.web_url}/tree/"
            f"{_channel_source_sha(pack, channel) or config.default_branch}/{pack.relative_path}"
        ),
        "repository": config.web_url,
        "license": pack.license,
        "keywords": pack.keywords,
        "skills": "./skills/",
        "interface": {
            "displayName": pack.display_name,
            "shortDescription": (
                pack.short_description
                if len(pack.short_description) <= 120
                else textwrap.shorten(pack.short_description, width=120, placeholder="…")
            ),
            "longDescription": pack.description,
            "developerName": config.publisher_name,
            "category": pack.category,
            "capabilities": ["Read", "Write"],
            "websiteURL": (
                f"{config.web_url}/tree/"
                f"{_channel_source_sha(pack, channel) or config.default_branch}/"
                f"{pack.relative_path}"
            ),
            "defaultPrompt": [item["prompt"] for item in pack.starter_prompts],
        },
    }


def _claude_marketplace(
    config: RepositoryConfig,
    packs: list[Pack],
    *,
    channel: DistributionChannel = "public",
    self_contained: bool = False,
) -> dict:
    owner = {"name": config.publisher_name}
    if config.security_email:
        owner["email"] = config.security_email
    return {
        "name": config.marketplace_name,
        "owner": owner,
        "description": config.marketplace_description,
        "plugins": [
            {
                "name": pack.id,
                "source": _source(
                    config,
                    pack,
                    channel=channel,
                    local_path=f"./plugins/{pack.id}" if self_contained else None,
                ),
                "description": pack.short_description,
                "version": _channel_version(pack, channel),
                "author": {"name": config.publisher_name},
                "category": pack.category,
                "tags": pack.keywords,
                "strict": True,
            }
            for pack in packs
            if "claude-code" in pack.targets
        ],
    }


def _codex_marketplace(
    config: RepositoryConfig,
    packs: list[Pack],
    *,
    channel: DistributionChannel = "public",
    self_contained: bool = False,
) -> dict:
    return {
        "name": config.marketplace_name,
        "interface": {"displayName": config.marketplace_display_name},
        "plugins": [
            {
                "name": pack.id,
                "source": _source(
                    config,
                    pack,
                    channel=channel,
                    codex=True,
                    local_path=f"./plugins/{pack.id}" if self_contained else None,
                ),
                "policy": {
                    "installation": "AVAILABLE",
                    "authentication": "ON_INSTALL",
                },
                "category": pack.category,
            }
            for pack in packs
            if "codex" in pack.targets
        ],
    }


def _catalog(
    config: RepositoryConfig,
    packs: list[Pack],
    *,
    channel: DistributionChannel = "public",
) -> dict:
    return {
        "schemaVersion": 2,
        "project": config.project_name,
        "repository": config.slug,
        "marketplace": config.marketplace_name,
        "packs": [
            {
                "id": pack.id,
                "displayName": pack.display_name,
                "shortDescription": pack.short_description,
                "description": pack.description,
                "language": pack.language,
                "subject": pack.subject,
                "version": _channel_version(pack, channel),
                "tag": _channel_tag(pack, channel),
                "path": pack.relative_path,
                "license": pack.license,
                "skills": pack.skills,
                "targets": pack.targets,
                "category": pack.category,
                "keywords": pack.keywords,
                "compatibility": pack.compatibility,
                "operations": pack.operations,
                "publication": {
                    "state": pack.publication_state,
                    "visibility": pack.visibility,
                    "maturity": pack.maturity,
                    "sourceType": "git-subdir" if channel == "public" else "repo-local",
                    **(
                        {
                            "latestRelease": {
                                "version": pack.published_version,
                                "sourceSha": pack.source_sha,
                                "releaseId": pack.latest_release["release-id"],
                                "releasedAt": pack.latest_release["released-at"],
                            }
                        }
                        if pack.latest_release
                        else {}
                    ),
                },
            }
            for pack in packs
        ],
    }


def _pages_index(config: RepositoryConfig, catalog: dict) -> str:
    """Render the static Pages landing page from the generated catalog model."""

    pack_cards: list[str] = []
    for pack in catalog["packs"]:
        targets = [str(target) for target in pack["targets"]]
        target_items = "\n".join(
            f"              <li><code>{escape(target)}</code></li>" for target in targets
        )
        index_link = ""
        if "opencode" in targets:
            index_path = f"opencode/{pack['language']}/{pack['subject']}/index.json"
            index_link = (
                "\n"
                f'            <p><a href="{escape(index_path, quote=True)}">'
                "OpenCode index</a></p>"
            )
        publication = escape(str(pack["publication"]["state"]))
        tag = str(pack["tag"])
        latest_release = pack["publication"]["latestRelease"]
        source_sha = str(latest_release["sourceSha"])
        release_url = f"{config.web_url}/releases/tag/{tag}"
        commit_url = f"{config.web_url}/commit/{source_sha}"
        checksum_url = f"{config.web_url}/releases/download/{tag}/{tag}.zip.sha256"
        attestations_url = f"{config.web_url}/attestations"
        pack_cards.append(
            "\n".join(
                [
                    '        <article class="pack">',
                    f"          <h3>{escape(str(pack['displayName']))}</h3>",
                    "          <dl>",
                    "            <div>",
                    "              <dt>ID</dt>",
                    f"              <dd><code>{escape(str(pack['id']))}</code></dd>",
                    "            </div>",
                    "            <div>",
                    "              <dt>Version</dt>",
                    f"              <dd><code>{escape(str(pack['version']))}</code></dd>",
                    "            </div>",
                    "            <div>",
                    "              <dt>Publication</dt>",
                    f"              <dd><code>{publication}</code></dd>",
                    "            </div>",
                    "            <div>",
                    "              <dt>Tag</dt>",
                    (
                        f'              <dd><a href="{escape(release_url, quote=True)}">'
                        f"<code>{escape(tag)}</code></a></dd>"
                    ),
                    "            </div>",
                    "            <div>",
                    "              <dt>Source</dt>",
                    (
                        f'              <dd><a href="{escape(commit_url, quote=True)}">'
                        f"<code>{escape(source_sha)}</code></a></dd>"
                    ),
                    "            </div>",
                    "          </dl>",
                    f"          <p>{escape(str(pack['shortDescription']))}</p>",
                    "          <p>",
                    (
                        f'            <a href="{escape(release_url, quote=True)}">'
                        "Immutable release</a> · "
                        f'<a href="{escape(checksum_url, quote=True)}">SHA-256 checksum</a> · '
                        f'<a href="{escape(attestations_url, quote=True)}">'
                        "Verify attestations</a>"
                    ),
                    "          </p>",
                    "          <h4>Generated adapter targets</h4>",
                    '          <ul class="targets">',
                    target_items,
                    "          </ul>" + index_link,
                    "        </article>",
                ]
            )
        )

    return (
        "<!doctype html>\n"
        '<html lang="en">\n'
        "  <head>\n"
        '    <meta charset="utf-8">\n'
        '    <meta name="viewport" content="width=device-width, initial-scale=1">\n'
        f"    <title>{escape(str(catalog['project']))}</title>\n"
        "    <style>\n"
        "      :root { color-scheme: light dark; font-family: system-ui, sans-serif; }\n"
        "      body { margin: 0; }\n"
        "      main { margin: 0 auto; max-width: 72rem; padding: 2rem 1rem 4rem; }\n"
        "      header { border-bottom: 1px solid currentColor; margin-bottom: 2rem; }\n"
        "      .repository { font-family: ui-monospace, monospace; }\n"
        "      .packs { display: grid; gap: 1rem; grid-template-columns: repeat(auto-fit, "
        "minmax(18rem, 1fr)); }\n"
        "      .pack { border: 1px solid currentColor; border-radius: .5rem; padding: 1rem; }\n"
        "      .pack h3 { margin-top: 0; }\n"
        "      dl div { display: grid; grid-template-columns: 7rem 1fr; }\n"
        "      dd { margin: 0; }\n"
        "      .targets { display: flex; flex-wrap: wrap; gap: .75rem; padding-left: 1.25rem; }\n"
        "    </style>\n"
        "  </head>\n"
        "  <body>\n"
        "    <main>\n"
        "      <header>\n"
        f'        <p class="repository">{escape(str(catalog["repository"]))}</p>\n'
        f"        <h1>{escape(str(catalog['project']))}</h1>\n"
        f"        <p>{escape(config.project_description)}</p>\n"
        f"        <p>Marketplace: <code>{escape(str(catalog['marketplace']))}</code></p>\n"
        "      </header>\n"
        '      <section aria-labelledby="skillpacks-heading">\n'
        '        <h2 id="skillpacks-heading">Skillpacks</h2>\n'
        + (
            '        <div class="packs">\n' + "\n".join(pack_cards) + "\n        </div>\n"
            if pack_cards
            else "        <p><strong>No stable releases are currently published.</strong></p>\n"
        )
        + "      </section>\n"
        "    </main>\n"
        "  </body>\n"
        "</html>\n"
    )


def _root_catalog_markdown(config: RepositoryConfig, packs: list[Pack]) -> str:
    if not packs:
        return (
            "**No stable releases are currently published.** Public installation commands "
            "will appear here after an immutable release is reconciled."
        )
    rows = [
        "| Pack | Purpose | Skills | Version | Publication | Claude | Codex | OpenCode |",
        "|---|---|---:|---:|---|---|---|---|",
    ]
    for pack in packs:
        publication = "Published"
        rows.append(
            "| "
            f"[`{pack.id}`]({pack.relative_path}/README.md) | "
            f"{pack.short_description} | {len(pack.skills)} | "
            f"`{pack.published_version}` | "
            f"{publication} | "
            f"{'Plugin' if 'claude-code' in pack.targets else '—'} | "
            f"{'Plugin' if 'codex' in pack.targets else '—'} | "
            f"{'Installer + HTTP catalog' if 'opencode' in pack.targets else '—'} |"
        )
    rows.extend(
        [
            "",
            f"Marketplace: `{config.marketplace_name}`. Every public source pins both the "
            "pack-specific tag and its full release commit SHA.",
        ]
    )
    return "\n".join(rows)


def _routing_boundary_markdown(boundaries: tuple[RoutingBoundarySummary, ...]) -> str:
    rows = [
        "This table is generated from `evals/routing-boundaries.json`. `A` and `B` follow the",
        "lexicographically sorted skill IDs in each boundary.",
        "",
        "| Boundary | Shared vocabulary | A only | B only | Both | Neither |",
        "|---|---|---|---|---|---|",
    ]
    for boundary in boundaries:
        skill_a, skill_b = boundary.skills
        vocabulary = ", ".join(f"`{item}`" for item in boundary.shared_vocabulary)
        rows.append(
            f"| `{boundary.id}`<br>A: `${skill_a}`<br>B: `${skill_b}` | {vocabulary} | "
            f"`${skill_a}` | `${skill_b}` | both | none |"
        )
    rows.extend(
        [
            "",
            f"The {len(boundaries)} reviewed boundaries contain "
            f"{sum(len(boundary.cases) for boundary in boundaries)} cases: exactly one "
            "A-only, B-only, both, and neither prompt per boundary.",
        ]
    )
    return "\n".join(rows)


def _pack_install_markdown(config: RepositoryConfig, pack: Pack) -> str:
    is_published = pack.publication_state == "published" and pack.latest_release is not None
    if is_published:
        claude_marketplace_source = config.slug
        codex_marketplace_source = config.slug
        status = (
            f"Latest public release: `{pack.published_tag}`, pinned to `{pack.source_sha}` "
            "in generated "
            "marketplaces."
        )
    else:
        claude_marketplace_source = "dist/dev/claude"
        codex_marketplace_source = "dist/dev/codex"
        status = (
            "The marketplace source is repository-local and unpublished. Clone this "
            "repository and run these commands from its root; remote marketplace installation "
            "remains unavailable until post-release publication reconciliation. Run strict "
            "repository "
            "validation immediately before a local install so ignored cache files are not copied."
        )
    lines = [status, ""]

    if "claude-code" in pack.targets:
        lines.extend(
            [
                "### Claude Code",
                "",
                "```bash",
                f"claude plugin marketplace add {claude_marketplace_source}",
                f"claude plugin install {pack.id}@{config.marketplace_name}",
                "```",
                "",
            ]
        )
        if is_published:
            lines.extend(
                [
                    "Update the remote marketplace before installing an updated pack:",
                    "",
                    "```bash",
                    f"claude plugin marketplace update {config.marketplace_name}",
                    f"claude plugin update {pack.id}@{config.marketplace_name}",
                    "```",
                ]
            )
        else:
            lines.extend(
                [
                    "For local changes, regenerate this repository and reinstall the plugin:",
                    "",
                    "```bash",
                    f"claude plugin uninstall {pack.id}@{config.marketplace_name}",
                    f"claude plugin install {pack.id}@{config.marketplace_name}",
                    "```",
                ]
            )
        lines.extend(
            [
                "",
                "Uninstall:",
                "",
                "```bash",
                f"claude plugin uninstall {pack.id}@{config.marketplace_name}",
                "```",
                "",
            ]
        )

    if "codex" in pack.targets:
        lines.extend(
            [
                "### Codex",
                "",
                "```bash",
                f"codex plugin marketplace add {codex_marketplace_source}",
                f"codex plugin add {pack.id}@{config.marketplace_name}",
                "```",
                "",
            ]
        )
        if is_published:
            lines.extend(
                [
                    "Update by refreshing the remote marketplace and reinstalling the plugin:",
                    "",
                    "```bash",
                    f"codex plugin marketplace upgrade {config.marketplace_name}",
                    f"codex plugin remove {pack.id}@{config.marketplace_name}",
                    f"codex plugin add {pack.id}@{config.marketplace_name}",
                    "```",
                ]
            )
        else:
            lines.extend(
                [
                    "For local changes, regenerate this repository and reinstall the plugin:",
                    "",
                    "```bash",
                    f"codex plugin remove {pack.id}@{config.marketplace_name}",
                    f"codex plugin add {pack.id}@{config.marketplace_name}",
                    "```",
                ]
            )
        lines.extend(
            [
                "",
                "Uninstall:",
                "",
                "```bash",
                f"codex plugin remove {pack.id}@{config.marketplace_name}",
                "```",
                "",
            ]
        )

    if "opencode" in pack.targets:
        lines.extend(
            [
                "### OpenCode or optional direct install",
                "",
                (
                    "The direct installer uses the public-preview `gh skill` interface. It "
                    "checks the installed CLI before making changes; `--dry-run`/`-DryRun` "
                    "does not require or probe `gh`."
                ),
                "",
            ]
        )
        if is_published:
            lines.extend(
                [
                    "```bash",
                    (
                        f"bash dist/public/install/{pack.id}.sh --repository {config.slug} "
                        f"--agent opencode --scope user --pin {pack.source_sha}"
                    ),
                    "```",
                    "",
                    "PowerShell:",
                    "",
                    "```powershell",
                    (
                        f".\\dist\\public\\install\\{pack.id}.ps1 -Repository {config.slug} "
                        f"-Agent opencode -Scope user -Pin {pack.source_sha}"
                    ),
                    "```",
                    "",
                    f"The immutable default pin is `{pack.source_sha}`.",
                ]
            )
        else:
            lines.extend(
                [
                    (
                        "No executable remote install command is published before a release "
                        "SHA is recorded. Inspect the future exact-path operations locally:"
                    ),
                    "",
                    "```bash",
                    f"bash dist/dev/install/{pack.id}.sh --dry-run",
                    "```",
                    "",
                    "```powershell",
                    f".\\dist\\dev\\install\\{pack.id}.ps1 -DryRun",
                    "```",
                    "",
                    "The dry run does not install skills or make a compatibility claim.",
                ]
            )

    return "\n".join(lines).rstrip()


def _pack_lifecycle_markdown(pack: Pack) -> str:
    lines = [
        f"Current source version: `{pack.version}`.",
        "",
        f"Maturity: `{pack.maturity}`. Distribution visibility: `{pack.visibility}`. "
        f"Publication state: `{pack.publication_state}`.",
        "",
        f"Current derived tag: `{pack.tag}`.",
    ]
    if pack.latest_release:
        lines.extend(
            [
                "",
                f"Latest immutable public release: `{pack.published_tag}` at "
                f"`{pack.source_sha}` (release ID `{pack.latest_release['release-id']}`).",
            ]
        )
    if pack.visibility == "maintainers":
        claim = "This maintainer-only pack is ineligible for formal public release."
    elif pack.publication_state == "withdrawn":
        claim = "This pack is withdrawn and absent from every installable public surface."
    elif pack.maturity == "stable" and pack.publication_state == "unpublished":
        claim = (
            "This stable source is ready for exact-SHA native evidence; no public installation "
            "or compatibility claim exists before immutable release and reconciliation."
        )
    elif pack.publication_state == "unpublished":
        claim = "No public installation or native-client/model compatibility is claimed yet."
    else:
        claim = (
            "Public distribution remains pinned to the latest immutable release and its "
            "attached exact-SHA evidence."
        )
    lines.extend(["", claim])
    return "\n".join(lines)


def _bash_installer(config: RepositoryConfig, pack: Pack, *, channel: DistributionChannel) -> str:
    skills = "\n".join(f'  "{skill}"' for skill in pack.skills)
    source_sha = _channel_source_sha(pack, channel)
    default_pin = source_sha or "UNPUBLISHED"
    unpublished = 0 if source_sha else 1
    return f"""#!/usr/bin/env bash
# Generated by tools/generate-installers. Do not edit by hand.
set -euo pipefail

repository="${{GENAPTIC_SKILLSETS_REPOSITORY:-{config.slug}}}"
agent="opencode"
scope="user"
pin="${{GENAPTIC_SKILLSETS_REF:-{default_pin}}}"
force=0
dry_run=0
unpublished={unpublished}

usage() {{
  cat <<'EOF'
Install the {pack.display_name} skillpack with GitHub CLI.

Usage:
  {pack.id}.sh [options]

Options:
  --repository ORG/PROJECT  Source repository.
  --agent AGENT             Target agent (default: opencode).
  --scope SCOPE             user or project (default: user).
  --pin REF                 Pack tag or full commit SHA.
  --force                   Overwrite installed skills.
  --dry-run                 Print commands without executing them.
  -h, --help                Show this help.

The installer invokes only the public-preview `gh skill install` interface. It checks both
`gh skill --help` and `gh skill install --help` before making changes. Dry runs do not require
or probe `gh`. Every probe and install invocation sets `GH_TELEMETRY=false`,
`GH_PROMPT_DISABLED=1`, and `GH_NO_UPDATE_NOTIFIER=1` for that invocation only. The installer
does not execute bundled skill scripts.
EOF
}}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repository) repository="${{2:?missing value for --repository}}"; shift 2 ;;
    --agent) agent="${{2:?missing value for --agent}}"; shift 2 ;;
    --scope) scope="${{2:?missing value for --scope}}"; shift 2 ;;
    --pin) pin="${{2:?missing value for --pin}}"; shift 2 ;;
    --force) force=1; shift ;;
    --dry-run) dry_run=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

[[ "$repository" =~ ^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$ ]] || {{
  echo "--repository must use ORG/PROJECT format." >&2
  exit 2
}}
[[ "$scope" == "user" || "$scope" == "project" ]] || {{
  echo "--scope must be user or project." >&2
  exit 2
}}
[[ -n "$agent" && "$agent" != -* ]] || {{
  echo "--agent must be a non-empty agent identifier." >&2
  exit 2
}}
[[ -n "$pin" && "$pin" != -* ]] || {{
  echo "--pin must be a tag or full commit SHA." >&2
  exit 2
}}
[[ "$dry_run" -eq 1 || "$pin" != "UNPUBLISHED" ]] || {{
  echo "This pack is unpublished; pass --pin with a reviewed full commit SHA." >&2
  exit 2
}}
if [[ "$dry_run" -eq 0 && "$unpublished" -eq 1 && ! "$pin" =~ ^[0-9a-fA-F]{{40}}$ ]]; then
  echo "Unpublished packs require --pin with a full 40-character commit SHA." >&2
  exit 2
fi

if [[ "$dry_run" -eq 0 ]]; then
  if ! command -v gh >/dev/null 2>&1; then
    echo "GitHub CLI (gh) is not installed; the optional direct installer is unavailable." >&2
    exit 127
  fi
  if ! GH_TELEMETRY=false GH_PROMPT_DISABLED=1 GH_NO_UPDATE_NOTIFIER=1 gh skill --help >/dev/null 2>&1; then
    echo "Installed GitHub CLI does not support the public-preview 'gh skill' command." >&2
    exit 1
  fi
  if ! GH_TELEMETRY=false GH_PROMPT_DISABLED=1 GH_NO_UPDATE_NOTIFIER=1 gh skill install --help >/dev/null 2>&1; then
    echo "Installed GitHub CLI does not support the public-preview 'gh skill install' command." >&2
    exit 1
  fi
fi

skills=(
{skills}
)

for skill in "${{skills[@]}}"; do
  path="{pack.relative_path}/skills/$skill"
  command=(gh skill install "$repository" "$path" --agent "$agent" --scope "$scope" --pin "$pin")
  if [[ "$force" -eq 1 ]]; then
    command+=(--force)
  fi
  if [[ "$dry_run" -eq 1 ]]; then
    printf '%q ' "${{command[@]}}"
    printf '\\n'
  else
    printf 'Installing %s for %s at %s scope...\\n' "$skill" "$agent" "$scope"
    GH_TELEMETRY=false GH_PROMPT_DISABLED=1 GH_NO_UPDATE_NOTIFIER=1 "${{command[@]}}"
  fi
done
"""


def _powershell_installer(
    config: RepositoryConfig, pack: Pack, *, channel: DistributionChannel
) -> str:
    skills = ",\n    ".join(f'"{skill}"' for skill in pack.skills)
    source_sha = _channel_source_sha(pack, channel)
    default_pin = source_sha or "UNPUBLISHED"
    unpublished = "$true" if not source_sha else "$false"
    return f"""# Generated by tools/generate-installers. Do not edit by hand.
[CmdletBinding(SupportsShouldProcess = $true)]
param(
    [ValidatePattern('^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$')]
    [string]$Repository = $(if ($env:GENAPTIC_SKILLSETS_REPOSITORY) {{
        $env:GENAPTIC_SKILLSETS_REPOSITORY
    }} else {{
        "{config.slug}"
    }}),

    [ValidateNotNullOrEmpty()]
    [string]$Agent = "opencode",

    [ValidateSet("user", "project")]
    [string]$Scope = "user",

    [ValidateNotNullOrEmpty()]
    [string]$Pin = $(if ($env:GENAPTIC_SKILLSETS_REF) {{
        $env:GENAPTIC_SKILLSETS_REF
    }} else {{
        "{default_pin}"
    }}),

    [switch]$Force,
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"
$NativeErrorPreference = Get-Variable `
    -Name PSNativeCommandUseErrorActionPreference `
    -ErrorAction SilentlyContinue
if ($null -ne $NativeErrorPreference) {{
    $PSNativeCommandUseErrorActionPreference = $false
}}
$Unpublished = {unpublished}

if (-not $DryRun -and $Pin -eq "UNPUBLISHED") {{
    throw "This pack is unpublished; pass -Pin with a reviewed full commit SHA."
}}
if (-not $DryRun -and $Unpublished -and $Pin -notmatch '^[0-9a-fA-F]{{40}}$') {{
    throw "Unpublished packs require -Pin with a full 40-character commit SHA."
}}

$GhCommand = $null
if (-not $DryRun) {{
    $GhCommand = @(Get-Command gh -CommandType Application -ErrorAction SilentlyContinue)[0]
    if (-not $GhCommand) {{
        Write-Error -Message (
            "GitHub CLI (gh) is not installed; the optional direct installer is unavailable."
        ) -ErrorAction Continue
        exit 127
    }}
}}

$skills = @(
    {skills}
)

$GhEnvironment = [ordered]@{{
    "GH_TELEMETRY" = "false"
    "GH_PROMPT_DISABLED" = "1"
    "GH_NO_UPDATE_NOTIFIER" = "1"
}}
$GhEnvironmentSnapshot = @{{}}

if (-not $DryRun) {{
    foreach ($name in $GhEnvironment.Keys) {{
        $entry = Get-Item -LiteralPath "Env:$name" -ErrorAction SilentlyContinue
        $GhEnvironmentSnapshot[$name] = [pscustomobject]@{{
            Present = $null -ne $entry
            Value = if ($null -ne $entry) {{ $entry.Value }} else {{ $null }}
        }}
    }}
}}

try {{
    if (-not $DryRun) {{
        foreach ($name in $GhEnvironment.Keys) {{
            Set-Item -LiteralPath "Env:$name" -Value $GhEnvironment[$name]
        }}

        & $GhCommand.Source "skill" "--help" *> $null
        if ($LASTEXITCODE -ne 0) {{
            throw "Installed GitHub CLI does not support the public-preview 'gh skill' command."
        }}
        & $GhCommand.Source "skill" "install" "--help" *> $null
        if ($LASTEXITCODE -ne 0) {{
            throw (
                "Installed GitHub CLI does not support the public-preview " +
                "'gh skill install' command."
            )
        }}
    }}

foreach ($skill in $skills) {{
    $path = "{pack.relative_path}/skills/$skill"
    $arguments = @(
        "skill", "install", $Repository, $path,
        "--agent", $Agent,
        "--scope", $Scope,
        "--pin", $Pin
    )
    if ($Force) {{
        $arguments += "--force"
    }}

    $display = "gh " + ($arguments | ForEach-Object {{
        if ($_ -match '[\\s"]') {{ '"' + ($_ -replace '"', '\\"') + '"' }} else {{ $_ }}
    }} ) -join " "

    if ($DryRun) {{
        Write-Output $display
        continue
    }}

    if ($PSCmdlet.ShouldProcess("$skill for $Agent at $Scope scope", $display)) {{
        & $GhCommand.Source @arguments
        if ($LASTEXITCODE -ne 0) {{
            throw "gh skill install failed for $skill with exit code $LASTEXITCODE."
        }}
    }}
}}
}} finally {{
    if (-not $DryRun) {{
        foreach ($name in $GhEnvironment.Keys) {{
            $snapshot = $GhEnvironmentSnapshot[$name]
            if ($snapshot.Present) {{
                Set-Item -LiteralPath "Env:$name" -Value $snapshot.Value
            }} else {{
                Remove-Item -LiteralPath "Env:$name" -ErrorAction SilentlyContinue
            }}
        }}
    }}
}}
"""


def _installer_readme(
    config: RepositoryConfig,
    packs: list[Pack],
    *,
    channel: DistributionChannel,
) -> str:
    lines = [
        "# Generated direct installers",
        "",
        "These optional adapters are generated from `skillpack.yaml`. They install each declared",
        "skill by exact path with the public-preview `gh skill install` interface and require an",
        "immutable full commit SHA.",
        "",
        "They probe both `gh skill --help` and `gh skill install --help` before changing files.",
        "A missing or unsupported command is reported as unavailable; it is never a compatibility",
        "pass. Dry runs neither require nor probe `gh`.",
        "",
        "Each probe and install invocation sets `GH_TELEMETRY=false`, `GH_PROMPT_DISABLED=1`,",
        "and `GH_NO_UPDATE_NOTIFIER=1` in its process environment. PowerShell restores any prior",
        "values after the transaction. These controls do not imply broader network isolation.",
        "",
        "The installers do not run bundled helper scripts. Review a dry run before execution.",
        "",
        "| Pack | Bash | PowerShell | Publication / default pin |",
        "|---|---|---|---|",
    ]
    for pack in packs:
        lines.append(
            f"| `{pack.id}` | `{pack.id}.sh` | `{pack.id}.ps1` | "
            f"`{_channel_source_sha(pack, channel) or 'development; explicit SHA required'}` |"
        )
    lines.extend(
        [
            "",
            f"Default repository: `{config.slug}`.",
            "",
            "Review generated commands and the release before using `--force`.",
        ]
    )
    return "\n".join(lines) + "\n"


def _opencode_readme(packs: list[Pack], *, channel: DistributionChannel) -> str:
    lines = [
        "# Generated OpenCode V2 catalogs",
        "",
        "Each language/subject directory is an independently hostable HTTP catalog. Configure",
        'OpenCode with `{"skills":{"urls":["https://host/catalog/base/"]}}`.',
        "",
        "Each skill directory contains a literal `SKILL.md` plus its generated resources.",
        "Do not edit this directory by hand.",
        "",
        "| Pack | Catalog path | Version |",
        "|---|---|---|",
    ]
    for pack in packs:
        lines.append(
            f"| `{pack.id}` | `{pack.language}/{pack.subject}/index.json` | "
            f"`{_channel_version(pack, channel)}` |"
        )
    return "\n".join(lines) + "\n"


def _is_runtime_file(path: Path, skill_dir: Path) -> bool:
    relative = path.relative_to(skill_dir)
    return runtime_resource_is_allowed(relative)


def _skill_relative_posix(path: PurePath, skill_dir: PurePath) -> str:
    """Return a platform-independent ordering key for one skill resource."""

    return path.relative_to(skill_dir).as_posix()


def _runtime_files(root: Path, skill_dir: Path) -> list[Path]:
    paths: list[Path] = []
    for subdir in ("references", "assets", "scripts"):
        folder = skill_dir / subdir
        snapshot = walk_tree(folder, root, allow_missing=True)
        paths.extend(
            path for path, _metadata in snapshot.files if _is_runtime_file(path, skill_dir)
        )
    return sorted(paths, key=lambda path: _skill_relative_posix(path, skill_dir))


def _released_skill_files(root: Path, pack: Pack, skill: str) -> list[tuple[Path, bytes, int]]:
    """Return the released SKILL.md/runtime tree from the exact public source commit."""

    source_sha = pack.source_sha
    if not source_sha:
        raise SkillpackError(f"{pack.id}: released skill files require a source SHA.")
    skill_prefix = f"{pack.relative_path}/skills/{skill}"
    _commit, tree_oid = _exact_commit(root, source_sha)
    completed = _exact_git(
        root,
        "ls-tree",
        "-r",
        "-z",
        "--full-tree",
        tree_oid,
        "--",
        skill_prefix,
    )
    if completed.returncode:
        detail = completed.stderr.decode("utf-8", errors="replace").strip()
        raise SkillpackError(
            f"Could not enumerate released files for {pack.id}/{skill}: "
            f"{detail or 'missing object'}"
        )

    entries: list[tuple[Path, bytes, int]] = []
    for raw_path, mode, kind, object_id in _parse_tree_records(
        completed.stdout,
        label=f"{pack.id}/{skill} released tree",
    ):
        try:
            repository_path = Path(raw_path)
            relative = repository_path.relative_to(skill_prefix)
        except ValueError as exc:
            raise SkillpackError(
                f"{pack.id}/{skill}: malformed or unsafe released Git tree entry."
            ) from exc
        if kind != "blob" or mode not in {"100644", "100755"}:
            raise SkillpackError(
                f"{pack.id}/{skill}: released runtime entries must be regular files."
            )
        include = relative == Path("SKILL.md") or (
            relative.parts
            and relative.parts[0] in {"references", "assets", "scripts"}
            and runtime_resource_is_allowed(relative)
        )
        if not include:
            continue
        entries.append(
            (
                relative,
                _git_blob(
                    root,
                    object_id,
                    label=f"{pack.id}/{skill}:{repository_path.as_posix()}",
                ),
                0o755 if mode == "100755" else 0o644,
            )
        )
    if not any(relative == Path("SKILL.md") for relative, _content, _mode in entries):
        raise SkillpackError(f"{pack.id}/{skill}: released tree has no literal SKILL.md.")
    return sorted(entries, key=lambda item: item[0].as_posix())


def _tracked_source_modes(root: Path) -> dict[str, int]:
    """Return Git-index modes once so generation remains fast and cross-platform."""

    try:
        result = subprocess.run(
            [
                "git",
                "-c",
                "core.longpaths=true",
                "-C",
                str(root),
                "ls-files",
                "--stage",
                "-z",
            ],
            check=False,
            capture_output=True,
            text=True,
        )
    except OSError:
        return {}
    if result.returncode != 0:
        return {}
    modes: dict[str, int] = {}
    for entry in result.stdout.split("\0"):
        if not entry or "\t" not in entry:
            continue
        metadata, relative = entry.split("\t", 1)
        index_mode = metadata.split(maxsplit=1)[0]
        modes[relative] = 0o755 if index_mode == "100755" else 0o644
    return modes


def _portable_source_mode(
    root: Path, path: Path, tracked_modes: dict[str, int] | None = None
) -> int:
    """Read executable intent portably, even when Git metadata is unavailable."""

    try:
        relative = path.relative_to(root).as_posix()
    except ValueError:
        relative = ""
    modes = tracked_modes if tracked_modes is not None else _tracked_source_modes(root)
    if relative in modes:
        return modes[relative]
    if read_regular_bytes(path, root).startswith(b"#!/"):
        return 0o755
    metadata = inspect_path(path, root, leaf_kind="file")
    assert metadata is not None
    return 0o755 if metadata.st_mode & 0o111 else 0o644


def _add_skill_tree(
    files: GeneratedFiles,
    root: Path,
    pack: Pack,
    destination: Path,
    tracked_modes: dict[str, int],
    *,
    include_openai_sidecar: bool,
) -> None:
    for skill in pack.skills:
        skill_dir = pack.path / "skills" / skill
        inputs = [skill_dir / "SKILL.md", *_runtime_files(root, skill_dir)]
        if include_openai_sidecar:
            inputs.append(skill_dir / "agents" / "openai.yaml")
        for source in sorted(
            inputs,
            key=lambda source: _skill_relative_posix(source, skill_dir),
        ):
            relative = source.relative_to(skill_dir)
            files.add(
                (destination / skill / relative).as_posix(),
                read_regular_bytes(source, root),
                mode=_portable_source_mode(root, source, tracked_modes),
            )


def _add_self_contained_marketplaces(
    files: GeneratedFiles,
    root: Path,
    config: RepositoryConfig,
    packs: list[Pack],
    tracked_modes: dict[str, int],
    *,
    channel: DistributionChannel,
    destination: Path,
) -> None:
    claude = [pack for pack in packs if "claude-code" in pack.targets]
    codex = [pack for pack in packs if "codex" in pack.targets]
    files.add(
        (destination / "claude/.claude-plugin/marketplace.json").as_posix(),
        json_text(_claude_marketplace(config, claude, channel=channel, self_contained=True)),
    )
    files.add(
        (destination / "codex/.agents/plugins/marketplace.json").as_posix(),
        json_text(_codex_marketplace(config, codex, channel=channel, self_contained=True)),
    )
    for pack in claude:
        plugin_root = destination / "claude/plugins" / pack.id
        files.add(
            (plugin_root / ".claude-plugin/plugin.json").as_posix(),
            json_text(_claude_plugin(config, pack, channel)),
        )
        _add_skill_tree(
            files,
            root,
            pack,
            plugin_root / "skills",
            tracked_modes,
            include_openai_sidecar=False,
        )
    for pack in codex:
        plugin_root = destination / "codex/plugins" / pack.id
        files.add(
            (plugin_root / ".codex-plugin/plugin.json").as_posix(),
            json_text(_codex_plugin(config, pack, channel)),
        )
        _add_skill_tree(
            files,
            root,
            pack,
            plugin_root / "skills",
            tracked_modes,
            include_openai_sidecar=True,
        )


def _add_installers(
    files: GeneratedFiles,
    config: RepositoryConfig,
    packs: list[Pack],
    *,
    channel: DistributionChannel,
    destination: Path,
) -> None:
    opencode_packs = [pack for pack in packs if "opencode" in pack.targets]
    files.add(
        (destination / "README.md").as_posix(),
        _installer_readme(config, opencode_packs, channel=channel),
    )
    for pack in opencode_packs:
        files.add(
            (destination / f"{pack.id}.sh").as_posix(),
            _bash_installer(config, pack, channel=channel),
            mode=0o755,
        )
        files.add(
            (destination / f"{pack.id}.ps1").as_posix(),
            _powershell_installer(config, pack, channel=channel),
        )


def _add_opencode_catalogs(
    files: GeneratedFiles,
    root: Path,
    packs: list[Pack],
    tracked_modes: dict[str, int],
    *,
    channel: DistributionChannel,
    destination: Path,
) -> None:
    opencode_packs = [pack for pack in packs if "opencode" in pack.targets]
    files.add(
        (destination / "README.md").as_posix(),
        _opencode_readme(opencode_packs, channel=channel),
    )
    for pack in opencode_packs:
        catalog_base = destination / pack.language / pack.subject
        catalog_skills: list[dict[str, object]] = []
        for skill in pack.skills:
            skill_dir = pack.path / "skills" / skill
            target_prefix = catalog_base / skill
            if channel == "public":
                inputs = _released_skill_files(root, pack, skill)
            else:
                source_skill = skill_dir / "SKILL.md"
                inputs = [
                    (Path("SKILL.md"), read_regular_bytes(source_skill, root), 0o644),
                    *[
                        (
                            resource.relative_to(skill_dir),
                            read_regular_bytes(resource, root),
                            _portable_source_mode(root, resource, tracked_modes),
                        )
                        for resource in _runtime_files(root, skill_dir)
                    ],
                ]
            listed_files: list[str] = []
            for relative, content, mode in inputs:
                listed_files.append(relative.as_posix())
                files.add(
                    (target_prefix / relative).as_posix(),
                    content,
                    mode=mode,
                )
            catalog_skills.append(
                {
                    "name": skill,
                    "version": _channel_version(pack, channel),
                    "files": listed_files,
                }
            )
        files.add(
            (catalog_base / "index.json").as_posix(),
            json_text({"skills": catalog_skills}),
        )


def build_generated_files(root: Path) -> GeneratedFiles:
    root = Path(os.path.abspath(os.fspath(root)))
    config = load_repository(root)
    packs = discover_packs(root)
    if not packs:
        raise SkillpackError("No skillpack.yaml files were found under packs/*/*/.")
    tracked_modes = _tracked_source_modes(root)

    public_packs = [_published_snapshot(root, pack) for pack in select_packs(packs, "public")]
    preview_packs = select_packs(packs, "preview")
    development_packs = select_packs(packs, "development")
    boundary_errors, boundaries = validate_routing_boundaries(root, packs=packs)
    if boundary_errors:
        raise SkillpackError(
            "Routing-boundary validation failed:\n"
            + "\n".join(f"  - {error}" for error in boundary_errors)
        )

    files = GeneratedFiles()
    for pack in packs:
        if "claude-code" in pack.targets:
            files.add(
                f"{pack.relative_path}/.claude-plugin/plugin.json",
                json_text(_claude_plugin(config, pack, "development")),
            )
        if "codex" in pack.targets:
            files.add(
                f"{pack.relative_path}/.codex-plugin/plugin.json",
                json_text(_codex_plugin(config, pack, "development")),
            )

    files.add(
        ".claude-plugin/marketplace.json",
        json_text(_claude_marketplace(config, public_packs, channel="public")),
    )
    files.add(
        ".agents/plugins/marketplace.json",
        json_text(_codex_marketplace(config, public_packs, channel="public")),
    )
    public_catalog = _catalog(config, public_packs, channel="public")
    files.add("catalog.json", json_text(public_catalog))
    files.add("dist/public/index.html", _pages_index(config, public_catalog))

    root_readme = read_regular_text(root / "README.md", root)
    files.add(
        "README.md",
        replace_marked_section(
            root_readme,
            GENERATED_BEGIN,
            GENERATED_END,
            _root_catalog_markdown(config, public_packs),
        ),
    )
    evals_document = read_regular_text(root / "docs" / "evals.md", root)
    files.add(
        "docs/evals.md",
        replace_marked_section(
            evals_document,
            BOUNDARY_MATRIX_BEGIN,
            BOUNDARY_MATRIX_END,
            _routing_boundary_markdown(boundaries),
        ),
    )

    for pack in packs:
        pack_readme_path = pack.path / "README.md"
        pack_readme_metadata = inspect_path(
            pack_readme_path,
            root,
            leaf_kind="file",
            allow_missing=True,
        )
        if pack_readme_metadata is not None:
            pack_readme = read_regular_text(pack_readme_path, root)
            files.add(
                f"{pack.relative_path}/README.md",
                replace_marked_section(
                    replace_marked_section(
                        pack_readme,
                        PACK_INSTALL_BEGIN,
                        PACK_INSTALL_END,
                        _pack_install_markdown(config, pack),
                    ),
                    PACK_LIFECYCLE_BEGIN,
                    PACK_LIFECYCLE_END,
                    _pack_lifecycle_markdown(pack),
                ),
            )

    if public_packs:
        _add_installers(
            files,
            config,
            public_packs,
            channel="public",
            destination=Path("dist/public/install"),
        )
        _add_opencode_catalogs(
            files,
            root,
            public_packs,
            tracked_modes,
            channel="public",
            destination=Path("dist/public/opencode"),
        )

    for channel, selected in (
        ("preview", preview_packs),
        ("development", development_packs),
    ):
        destination = Path("dist/preview" if channel == "preview" else "dist/dev")
        files.add(
            (destination / "catalog.json").as_posix(),
            json_text(_catalog(config, selected, channel=channel)),
        )
        _add_self_contained_marketplaces(
            files,
            root,
            config,
            selected,
            tracked_modes,
            channel=channel,
            destination=destination,
        )
        _add_installers(
            files,
            config,
            selected,
            channel=channel,
            destination=destination / "install",
        )
        _add_opencode_catalogs(
            files,
            root,
            selected,
            tracked_modes,
            channel=channel,
            destination=destination / "opencode",
        )

    manifest_entries = [
        {
            "path": path,
            "sha256": sha256_bytes(_as_bytes(content)),
            "size": len(_as_bytes(content)),
            "mode": f"{files.modes[path]:04o}",
        }
        for path, content in sorted(files.items())
        if path != "dist/generated-files.json"
    ]
    files.add(
        "dist/generated-files.json",
        json_text({"schemaVersion": 1, "files": manifest_entries}),
    )
    return files


def _reconcile_generated_files(
    root: Path,
    *,
    check: bool = False,
    expected: GeneratedFiles | None = None,
) -> tuple[list[str], GeneratedFiles]:
    """Reconcile generated files and return the authoritative generated snapshot."""

    root = Path(os.path.abspath(os.fspath(root)))
    if expected is not None and not check:
        raise SkillpackError("Generated snapshots may be reused only for read-only verification.")
    reusing_snapshot = expected is not None
    generation_inputs_before = _capture_generation_inputs(root)
    canonical_before = walk_tree(root / "packs", root)
    root_source_preimages = {
        path: inspect_path(path, root, leaf_kind="file")
        for path in (root / "repository.yaml", root / "README.md", root / "docs" / "evals.md")
    }
    if expected is None:
        expected = build_generated_files(root)
    else:
        _verify_generation_snapshot(root, expected, generation_inputs_before.state)
    changed: list[str] = []

    canonical_after = walk_tree(root / "packs", root)
    before_nodes = {
        repository_relative(path, root): metadata
        for path, metadata in (*canonical_before.directories, *canonical_before.files)
    }
    after_nodes = {
        repository_relative(path, root): metadata
        for path, metadata in (*canonical_after.directories, *canonical_after.files)
    }
    if set(before_nodes) != set(after_nodes) or any(
        not same_identity(metadata, after_nodes[path]) for path, metadata in before_nodes.items()
    ):
        raise SkillpackError("Canonical pack content changed during generation preflight.")
    generation_inputs_after = generation_inputs_before
    if not reusing_snapshot:
        generation_inputs_after = _capture_generation_inputs(root)
        if generation_inputs_after.state != generation_inputs_before.state:
            raise SkillpackError("Generation inputs changed during generation preflight.")
        before_preimages = dict(generation_inputs_before.preimages)
        after_preimages = dict(generation_inputs_after.preimages)
        if set(before_preimages) != set(after_preimages) or any(
            not same_identity(metadata, after_preimages[path])
            for path, metadata in before_preimages.items()
        ):
            raise SkillpackError("Generation input identities changed during generation preflight.")
    for path, preimage in root_source_preimages.items():
        assert preimage is not None
        verify_preimage(path, root, preimage)

    packs = discover_packs(root)
    generated_roots = [
        root / ".claude-plugin",
        root / ".agents" / "plugins",
        root / "dist" / "public",
        root / "dist" / "preview",
        root / "dist" / "dev",
        # Legacy roots are retained in cleanup for the schema-v2 migration only.
        root / "dist" / "install",
        root / "dist" / "opencode",
        *(pack.path / ".claude-plugin" for pack in packs),
        *(pack.path / ".codex-plugin" for pack in packs),
    ]

    input_preimages = dict(generation_inputs_after.preimages)
    expected_paths: dict[str, tuple[Path, os.stat_result | None]] = {}
    for relative in expected:
        raw_relative = Path(relative)
        if raw_relative.is_absolute() or ".." in raw_relative.parts:
            raise SkillpackError(f"Generated destination is not repository-relative: {relative!r}.")
        path = root / raw_relative
        normalized = repository_relative(path, root).as_posix()
        if normalized != raw_relative.as_posix():
            raise SkillpackError(f"Generated destination is not normalized: {relative!r}.")
        preimage = input_preimages.get(path)
        if preimage is None:
            preimage = inspect_path(path, root, leaf_kind="file", allow_missing=True)
        expected_paths[relative] = (path, preimage)

    cleanup_files: dict[Path, os.stat_result] = {}
    cleanup_directories: dict[Path, os.stat_result] = {}
    for generated_root in generated_roots:
        snapshot = walk_tree(generated_root, root, allow_missing=True)
        cleanup_files.update(snapshot.files)
        cleanup_directories.update(snapshot.directories)
    legacy_index = root / "dist" / "index.html"
    legacy_index_metadata = inspect_path(
        legacy_index,
        root,
        leaf_kind="file",
        allow_missing=True,
    )
    if legacy_index_metadata is not None:
        cleanup_files[legacy_index] = legacy_index_metadata

    rewritten_inputs: set[Path] = set()
    for relative, content in expected.items():
        path, preimage = expected_paths[relative]
        wanted = _as_bytes(content)
        metadata = verify_preimage(path, root, preimage)
        actual = read_regular_bytes(path, root) if metadata is not None else None
        actual_mode = metadata.st_mode & 0o777 if metadata is not None else None
        expected_mode = expected.modes[relative]
        mode_mismatch = os.name != "nt" and actual_mode != expected_mode
        if actual != wanted or mode_mismatch:
            changed.append(relative)
            if not check:
                if path in input_preimages:
                    rewritten_inputs.add(path)
                safe_atomic_write_bytes(
                    path,
                    wanted,
                    root,
                    mode=expected_mode,
                    expected=preimage,
                )

    expected_relative_paths = set(expected_paths)
    stale_files: list[tuple[Path, os.stat_result]] = []
    for path, metadata in cleanup_files.items():
        relative = repository_relative(path, root).as_posix()
        if relative not in expected_relative_paths:
            changed.append(relative)
            stale_files.append((path, metadata))

    if not check:
        for path, metadata in sorted(stale_files, key=lambda item: item[0].as_posix()):
            unlink_regular(path, root, expected=metadata)
        for directory, metadata in sorted(
            cleanup_directories.items(),
            key=lambda item: (len(item[0].parts), item[0].as_posix()),
            reverse=True,
        ):
            remove_empty_directory(directory, root, expected=metadata)

    if check and changed:
        detail = "\n".join(f"  - {path}" for path in sorted(set(changed)))
        raise SkillpackError(
            "Generated files are missing or stale. Run `python3 tools/generate-all`:\n" + detail
        )
    intended_final_state = _expected_post_reconciliation_state(
        generation_inputs_after.state,
        expected,
    )
    final_inputs = _capture_generation_inputs(root)
    if final_inputs.state != intended_final_state:
        raise SkillpackError("Generation inputs changed during generated-file reconciliation.")
    final_preimages = dict(final_inputs.preimages)
    preserved_preimages = dict(generation_inputs_after.preimages)
    for path, metadata in preserved_preimages.items():
        if path in rewritten_inputs:
            continue
        final_metadata = final_preimages.get(path)
        if final_metadata is None or not same_identity(metadata, final_metadata):
            relative = repository_relative(path, root).as_posix()
            raise SkillpackError(
                f"Generation input identity changed during reconciliation: {relative}."
            )
    if reusing_snapshot:
        _verify_generation_snapshot(root, expected, final_inputs.state)
    _bind_generation_snapshot(root, expected, final_inputs.state)
    return sorted(set(changed)), expected


def apply_generated_files(root: Path, *, check: bool = False) -> list[str]:
    """Write or check generated files while preserving the established list-returning API."""

    changed, generated = _reconcile_generated_files(root, check=check)
    return GeneratedChanges(changed, generated)
